### ISSUE TITLE
우리도 라벨을 달고 만들 수 있을까요?

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#1]

**Comment by jmg7173** [comment]
엉엉 안되네요 ㅠㅠ

**Comment by minhoryang** [comment]
짐전에게 권한을 줫어요!

**Comment by minhoryang** [comment]
![사진사진](http://f.cl.ly/items/0b453v3M0e3X453e2I3U/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202016-03-13%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%209.41.56.png)
https://github.com/orgs/SGCSRelease/people 이 곳에 들어가면 SGCSRelease의 관리자 목록이 있구요. (+짐전)

![](http://f.cl.ly/items/150j190V1b342T471r0W/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202016-03-13%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%209.44.09.png)
https://github.com/orgs/SGCSRelease/teams 여기의 "릴리즈회원"에 등록된 사람은 자동으로 SGCSRelease/ReleaseWorld의 쓰기권한을 얻어요. 그래서 라벨을 달 수 있을 거에요!

한번 실험해봐요.

**Comment by juice500ml** [comment]
오옹 됩니다!

**Comment by juice500ml** [comment]
@minhoryang 
@JimJeon 을 Member로 바꾸고, 오직 AwesomeTitle과 ReleaseWorld Admin 권한만 주는 것으로 바꾸었습니다.

**Comment by JimJeon** [comment]
여기 닫겠습니다.

**Comment by minhoryang** [comment]
다들 잘 되시는거죠? 감사합니다!

**Comment by JimJeon** [comment]
이 내용은  #11 이러한 wiki를 만들면서 포함시키면 좋을 것 같아요!
@jmg7173 @yunitto @tmdghks0612
