### ISSUE TITLE
대내기획/대외기획 구분 기준이 불명확한 듯 합니다.

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#10]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160320`
- **관련된 이슈들**:
  - 부모 이슈:   `null`
  - 자식 이슈:   `null`
- **추천하고 싶은 사람**:  @JimJeon 
#### 설명:

Issue #6 의 경우, 대상을 보면 오직 외부 인원이지만, 대내기획의 자식 기획입니다.
목적 기준으로, 대내기획을 하기 위해서라는 부분에서는 대내기획이라는 생각이 들었으나
기능 기준으로, 대외 사람들과의 컨택만이 필요한 부분이므로 대외기획이라는 생각도 듭니다.
어떻게 생각하시나요?
다른 Assignee분들도 생각해보아주세요.
@yunitto @jmg7173 @tmdghks0612 
#### 확인:
- [x] **@JimJeon**

**Comment by JimJeon** [comment]
이전 이슈인 #6 를 예를 들자면

생각해 볼 관점은
- 진행자와 식당
- 진행자와 대상자
- 대상자와 식당

이렇게 세 가지 인 것 같습니다.

분명 대상자는 릴리즈 내부인원이 관계되어 있지만
issue 제목처럼 뒷풀이 장소 예약의 진행과정에서 이루어지는 일은
진행자와 식당의 관계가 가장 크다고 생각되어 대외기획으로 처리하였습니다.

이 부분에 대해서 모호한 부분들을 **언어화**하고 **문서화**하는 작업이 필요할 듯 싶습니다.

다음 분들이 도와주셨으면 좋겠습니다.
- [ ] @tmdghks0612 
- [x] @jmg7173 
- [ ] @yunitto

**Comment by yunitto** [comment]
음 굳이 대내기획과 대외기획을 나눌 필요는 없을것같아요. 이번처럼 기준이 불명확한 경우도 생기구요. 차라리 `외부컨택필요` 라는 라벨을 만드는게 어떨까요?
@juice500ml 어떻게 생각하세요?

**Comment by juice500ml** [comment]
@yunitto `외부컨택` 라벨은 정말 좋은 아이디어인듯! @JimJeon 추가해도 좋을 것 같은데요?
@yunitto 대내와 대외를 굳이 나눈 이유가 일을 세분화하기 위해서라고 생각했는데, 사실 둘 다 사라져버리면 1. 더 깔끔해질 수도 있고 2. 기획 레이블이 엄청나게 범람할지도 몰라요. 차라리 하는 일 기준으로 쪼개도 좋아보이는데, 애매한 부분이 있거든요.  `선발` `세미나` `스터디` `프로젝트` `친목행사` 등등... 애매하네요

**Comment by JimJeon** [comment]
우선 그러면 대외, 대내 행사 라벨을 외부컨택 하나로 합치겠습니다!

**Comment by juice500ml** [comment]
저 다섯개 말고 추가가 될 것이 없다면 사실 저렇게 다섯개로 쪼개도 되는데... 더 필요한게 있을까요?

**Comment by JimJeon** [comment]
개강총회 같은 '공식행사' 라벨이 필요할 듯 싶습니다.

**Comment by juice500ml** [comment]
개총은 친목행사에 가깝지않나요?

**Comment by yunitto** [comment]
@juice500ml 이번 개총은 릴리즈 한학기 일정 소개와 관리 교육이 주 내용입니다. 친목도 물론 있구요!

**Comment by yunitto** [comment]
라벨을 어떻게 붙일지는 일단 내일 개총 끝나고 임원진이 모여서 회의해보겠습니다.

**Comment by juice500ml** [comment]
:+1:

**Comment by juice500ml** [comment]
회의 끝났나요? @yunitto

**Comment by yunitto** [comment]
대내기획/대외기획 구분을 없애고 행사별로 나누기로 했습니다
세미나/스터디 처럼요!
