### ISSUE TITLE
Github Issues for dummies를 만들어주세요!

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#11]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160320`
- **관련된 이슈들**:
  - 부모 이슈:   #1
  - 자식 이슈:   #1, ...
- **추천하고 싶은 사람**:  @jmg7173 @JimJeon @yunitto @tmdghks0612
#### 설명:

깃허브를 먼저 써보신 분들만 일단 태그했습니다.
현재 Wiki는 규칙 위주로 적혀있어서 다소 불친절한 것 같습니다.
규칙 말고 "방법" 위주의 위키를 만들어주세요.
처음 해보는 사람들은 다소 애매한 부분이 있는 것 같습니다.
#### 확인:
- [x] **@JimJeon**
- [x] @yunitto

**Comment by JimJeon** [comment]
한번에.. 여러명 assign이 안되는구...나...

**Comment by JimJeon** [comment]
이 부분은 혜수누나에게 맡기겠습니다.
저기 추천 받은사람들 다 끌어다 써도 되욥!

**Comment by minhoryang** [comment]
어떤점이 궁금하실까요?ㅇㅅㅇ

**Comment by JimJeon** [comment]
1. 깃허브 이슈에 관하여
   - 이슈는 어떻게 만들죠?
   - 이슈에서 할 수 있는 일이 무엇이 있죠?
   - etc.
2. 멤버는 무슨 일을 할 수 있죠?
3. 이곳에서는 무엇을 하나요?
4. 어떤 것들에서 알림이 오고 어떤 것들에서 오지 않나요?
5. etc.

이런 것들을 궁금해 하지 않을까요?

**Comment by yunitto** [comment]
음 굳이 github issues for dummies가 필요한 이유가 뭔가요? 운영진만 쓰는게 아닌가요?

**Comment by JimJeon** [comment]
릴리즈 회원 전체가 쓸 예정입니다.

라고 알고있어요....

**Comment by juice500ml** [comment]
@yunitto 
운영진이 꼭 깃을 잘 써봤던 사람이라는 보장이 없으니까요! 그리고 필요하다고 생각하는 것들은 Github Issue 탭을 통해 바로바로 들을 수 있도록 하고 싶어요

**Comment by JimJeon** [comment]
운영진만 쓰는건가요? !!!

**Comment by juice500ml** [comment]
그리고 필요하다고 생각하는 것들은 **릴리즈 회원 전체가** Github Issue 탭을 통해 바로바로 들을 수 있도록 하고 싶어요

**Comment by JimJeon** [comment]
왜 이런 질문을 하냐면 벌써 초대된 릴리즈 일반회원이 존재하기 때문입니다.

**Comment by juice500ml** [comment]
넵넵 제일 나은 시나리오는 릴리즈 전인원이 여기 가입하는거겠죠?

**Comment by JimJeon** [comment]
그렇게 되면 일반 회원과 운영진의 권한 구분이 있었으면 합니다!

**Comment by juice500ml** [comment]
깃허브 기능상 못해요!

**Comment by juice500ml** [comment]
아니면 운영진에게 짐전권한을 다 줘버리는 방법도..

**Comment by yunitto** [comment]
@juice500ml 그러면 모든 회원이 열람하고 이슈를 올릴수 있게 하되 누군가에게 일을 assign 하는 권한은 운영진 여섯명(승환, 민교, 윤영, 일선, 혜수, 짐전) 에게만 주어지게 하는건 어떨까요?

**Comment by juice500ml** [comment]
@yunitto 그게 합리적인 것 같긴 한데...ㅋㅋㅋㅋ 애매하네요 일단 그렇게 돌려보는것도 괜찮을 것 같은데요?

**Comment by juice500ml** [comment]
@yunitto 진행되고 있나요?

**Comment by juice500ml** [comment]
위키 업데이트는 되고있는건가요?

**Comment by minhoryang** [comment]
무서워욧!

**Comment by yunitto** [comment]
위키 업데이트는 했고, 주요 업무는 운영진이 맡아 하되 의견은 모든 학회원이 낼 수 있도록 하겠습니다. 릴리즈데이에 깃허브세미나를 통해 깃허브에 좀더 익숙해질 수 있을거에요. 권한은 모든 운영진에게 다 있나요? 권한 배분 후에 이슈 클로즈 부탁드릴게요 @juice500ml

**Comment by yunitto** [comment]
권한 관련해서 위키는 제가 내일 수정할게욧

**Comment by juice500ml** [comment]
@yunitto 권한은 현재 @JimJeon 에게만 있어요. 권한을 누구까지 주는게 맞을까요?

**Comment by JimJeon** [comment]
Moderator의 기능을 깃관련 전체 총괄로 하고
운영진 전부에게 기능을 주는것도 괜찮다고 생각해요.
깃에서 권한을 세 단계로 나누는게 안된다면 말이에요!

**Comment by juice500ml** [comment]
운영진 전부 @yunitto @tmdghks0612 @chldlftjs @charcoalbug @jmg7173 @JimJeon 이렇게 여섯 맞나요?

**Comment by JimJeon** [comment]
네 맞습니다.

**Comment by juice500ml** [comment]
https://github.com/orgs/SGCSRelease/teams/16-spring
ReleaseWorld Repo에 대한 Admin 권한을 주었습니다.
