### ISSUE TITLE
회칙 개정

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#12]
- [x] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈:   #2 
  - 자식 이슈:  
- **추천하고 싶은 사람**:  최윤영,@charcoalbug 최승환,@tmdghks0612
#### 설명:

회칙 개정안을 문서화할 것입니다.
문서화한 뒤에는 개총에서 투표를 통해 회칙 개정여부가 결정됩니다.
#### 확인:
- [x] **@JimJeon**
- [x] @tmdghks0612 
- [x] @charcoalbug

**Comment by minhoryang** [comment]
회칙을 마크다운으로 바꾸는데 사람이 필요하다면 저를 사용해주세욧!

**Comment by minhoryang** [comment]
어떤 회칙을 개정할 건가요?

**Comment by JimJeon** [comment]
이번 학기 새로 생긴 임원진 (운영진)과 깃에 대한 회칙을 개정하면 좋을 듯 합니다.

**Comment by minhoryang** [comment]
1. **기존에 있는 팀에 대한 언급 (새로 생긴 임원진을 위한 수정 부분)**
   - 제7장-학회의-구성 https://github.com/SGCSRelease/ReleaseWorld/blob/master/CODEOFCONDUCT.md#제7장-학회의-구성
2. **[오타] 인사팀 말고, 인사부가 2번 적혀져 있네요.** 그냥 고치면 될 것 같아요.
   - 제16조-자진-탈퇴 https://github.com/SGCSRelease/ReleaseWorld/blob/master/CODEOFCONDUCT.md#제16조-자진-탈퇴
   - 제8조-벌점의-관리 https://github.com/SGCSRelease/ReleaseWorld/blob/master/CODEOFCONDUCT.md#제8조-벌점의-관리
3. **수퍼루키에 대한 언급**
   - 제15조-프로젝트의-의무 https://github.com/SGCSRelease/ReleaseWorld/blob/master/CODEOFCONDUCT.md#제15조-프로젝트의-의무
   - 제30조-수퍼루키의-정의 https://github.com/SGCSRelease/ReleaseWorld/blob/master/CODEOFCONDUCT.md#제30조-수퍼루키의-정의
4. **[사물함] 을 위한 회칙**이 필요할 것 같습니다.
5. **[릴리즈 기자재 및 도서]에 대한 회칙**이 필요할 것 같습니다. (이제는 도서 대여는 안하나요?)
6. **[릴리즈 데이]를 위한 회칙**이 있나요?
   - 제1조-학회-모임-일정-확정 https://github.com/SGCSRelease/ReleaseWorld/blob/master/CODEOFCONDUCT.md#제1조-학회-모임-일정-확정
   
   ```
   학회 공식 전체 모임은 학회 초 전체 회의를 통해 일정을 확정한다.
   ```

**Comment by juice500ml** [comment]
하이고.. 개총 전에 이걸 했어야했던 것 같은데요 ㅠㅠ 회칙 개정 문제가 있었네요

**Comment by minhoryang** [comment]
개총에서 하는건 좀 그런가용?

**Comment by juice500ml** [comment]
@tmdghks0612 개총에서 정해진 부분 지금 커밋/푸쉬로 정리된건가요?

**Comment by juice500ml** [comment]
@tmdghks0612

**Comment by yunitto** [comment]
@tmdghks0612 확인해주세욧

**Comment by tmdghks0612** [comment]
오늘 커밋 푸시할게요!

**Comment by tmdghks0612** [comment]
완료!
