### ISSUE TITLE
회칙을 github와 google drive 중에 어디에 두는것이 좋을까요?

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#13]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 개강총회`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @tmdghks0612 
#### 설명:

추천인은 만약에 옮기게 되면 실행할 사람으로 정했습니다.

github에 올리게 되면 누가 언제 어느부분을 수정했는지가 나옵니다.
하지만 누구든 볼 수 있습니다!
어떻게 하는게 좋을지 의논해봅시다.

@릴리즈회원
#### 확인:
- [x] **@JimJeon**
- [ ] @tmdghks0612

**Comment by juice500ml** [comment]
모두가 봐도 좋은 것이니 커밋하고 히스토리를 관리하는게 좋아보여요!

**Comment by minhoryang** [comment]
회칙이 그렇게 자주 바뀌는 게 아니지만,
다른 사람들에게 보여주기에 매우 자랑스러우므로!
github가 더 의미 있을 것 같아요!

**Comment by yunitto** [comment]
저도 github가 더 좋을것같습니다!

**Comment by juice500ml** [comment]
@JimJeon 거의 확정된 이슈같으니 슬슬 클로즈해주세용~
@tmdghks0612 확정 이후로요!

**Comment by JimJeon** [comment]
@juice500ml 회칙이 깃으로 옮겨진 후에 클로즈 하겠습니다

**Comment by JimJeon** [comment]
제가 도와드릴테니 일선이형이 깃으로 회칙을 옮기는 것을 도와주셨으면 합니다.

markdown 문법은 @minhoryang 께서 가장 잘 아시고 계십니다.

**Comment by juice500ml** [comment]
@JimJeon 새로운 이슈로 파는게 좋지 않을까요? 이 이슈는 어디에 둘까요? 니까요~

**Comment by JimJeon** [comment]
귀찮아요

**Comment by juice500ml** [comment]
@JimJeon lol
