### ISSUE TITLE
릴리즈 명단이 있나요?

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/ReleaseWorld#14]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  160316 #신환회
- **관련된 이슈들**
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**: 
#### 설명:

릴리즈 명단이 있다면, **릴리즈원들만 볼 수 있도록 세팅된**, 구글독스 링크를 여기에 올려주세요!
#### 확인:
- [x] **@JimJeon**
- [ ] @Assignee

**Comment by JimJeon** [comment]
본 김에 끝내버리겠습니다.

**Comment by JimJeon** [comment]
이거도 명단을 작성해서 깃에 올리면 좋을거 같아요

**Comment by minhoryang** [comment]
@JimJeon 명단은 개인정보라서요 ㅎㅎ 구글드라이브 릴리즈 그룹 안에 저장해서,
그룹원만 볼 수 있도록 올려주세요!

**Comment by JimJeon** [comment]
그렇군요! 드라이브에 작성하겠습니다.

**Comment by JimJeon** [comment]
네 작성했습니다. 드라이브는 개강총회날에 이메일을 받아서 읽기권한으로 공유할 예정입니다.

**Comment by juice500ml** [comment]
@JimJeon @tmdghks0612 기수 정리한 김에 기수별로 명단을 만드는것도 좋아보여용

**Comment by JimJeon** [comment]
기수라면 방학 때 나 기타등등으로 추가된 사람들은 어떻게 정리하면 될까요?

**Comment by juice500ml** [comment]
만약 방학때 추가되신 분이면 방학때 활동은 공식 회원이 아닌 상태에서의 활동(인턴같은 느낌)에 가깝기 때문에 바로 다음 학기 개강총회때 기준으로 그때 들어온 신입생들과 같은 기수입니다.
