### ISSUE TITLE
이번 학기에는 릴리즈 후드 만드나요?

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/ReleaseWorld#15]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  모르겠어요!
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  김oo, @juice500ml
#### 설명:

릴리즈 후드는 예쁘고 좋아요!
올해도 예쁘게 만들어 보아요!
#### 확인:
- [x] **@JimJeon**
- [x] @tmdghks0612

**Comment by JimJeon** [comment]
대찬성입니다!

**Comment by yunitto** [comment]
과잠도 좋아여!!!!!!!

**Comment by minhoryang** [comment]
http://www.marpple.com/ 잠깐 홍보

**Comment by JimJeon** [comment]
이건 역시 학회장님이 추진해주셨으면 합니다.

**Comment by tmdghks0612** [comment]
개총 때 얘기해볼게요

**Comment by juice500ml** [comment]
@tmdghks0612 개총때 이야기해봤나요?

**Comment by minhoryang** [comment]
릴리즈데이에 한다고 했어욧

**Comment by tmdghks0612** [comment]
요즘 단체티 이것저것 찾아보고 있어요. 괜찮아 보이는 것들 추려서 릴리즈데이 때 투표를 해서 정하던지 그렇게 할 생각이에요.

**Comment by juice500ml** [comment]
@tmdghks0612 릴리즈데이보다도 활성원톡방이 나을것같아요 살 만한 전인원이 거기 있는거니까요. 그리고 깃헙 만든 이유가 진행 여부를 적기 위해서니까 **단체티를 찾아보고 있습니다**라는 말도 이슈에 남겨주시는게 나머지 사람들이 일하는데 편하겠죠?

**Comment by jmg7173** [comment]
클로즈하고 단체티 만드는 이슈 생성할게요
