### ISSUE TITLE
개강총회 PPT - 작년에 우리 릴리즈는 무슨 일을 했나요?

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/ReleaseWorld#16]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈:   #3
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @juice500ml, 정연준
#### 설명:

이것도 개총 PPT에 넣는게 좋 지 않을까요?
광희와 연준이가 잘 정리해 줄 거라고 생각해요!
#### 확인:
- [x] **@JimJeon**
- [x] @juice500ml

**Comment by juice500ml** [comment]
[**과거의 아쉬웠던 점** by @juice500ml (구글드라이브)](https://docs.google.com/document/d/1vaS2pDpo2okWrMA3oUbni1MgrqYEBgK1FHvEOPFpJiQ/edit?usp=sharing)

이 글을 참고해주세요!
@fuzzy (정연준)은 SP 끝나고 초대하겠습니다 ㅋㅋㅋ

@yunitto 누구와 이를 상의해야하나요?

**Comment by yunitto** [comment]
@juice500ml 딱히 상의할 내용은 없는 것 같고 무슨 행사를 대략적으로 했는지 승환이 @tmdghks0612 에게 알려주세요!
