### ISSUE TITLE
개강총회PPT- 이번 학기엔 뭘 하나요?

### ISSUE THREAD

**Issue by yunitto** [SGCSRelease/ReleaseWorld#17]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315 #신환회`
- **관련된 이슈들**:
  - 부모 이슈: #2 #3  
  - 연관 이슈: #8 #9 #16 
  - 자식 이슈: X
- **추천하고 싶은 사람**:  @tmdghks0612 
#### 설명:

이번 학기에 뭘 하는지 대략적인 계획을 월별로 소개해야해요!
단순히 해커톤이나 스터디가 아니라 한강소풍, 엠티 등등도 포함해서요.
#### 확인:
- [x] *_@tmdghks0612 *_

**Comment by minhoryang** [comment]
링크올려주세욧!
