### ISSUE TITLE
왜 저말고 다른 사람이 assign이 가능한 걸까요?

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#18]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @juice500ml @minhoryang 
#### 설명:

Moderator의 능력이 상실되었습ㄴ디ㅏ...

![2016-03-15 8 48 25](https://cloud.githubusercontent.com/assets/16199830/13776815/8180aa46-eaef-11e5-9e01-f3e39f0b5536.png)
#### 확인:
- [ ] **@JimJeon**
- [ ] @juice500ml

**Comment by minhoryang** [comment]
ㅠㅠ 미안해요.. 능력이 상실되었다기보다...ㅠㅠ Label과 Milestone을 지정하려면 관리자여야하는데요
그래서 모두가 Assign도 되는거죠.
Moderator가 가진 좋은 능력은 yunitto가 지정한 사람을 다른사람으로 바꿀 수 있다는 것이죠!

**Comment by JimJeon** [comment]
아하! 그렇군요!

**Comment by minhoryang** [comment]
+1 to your poooooooooooower!

**Comment by JimJeon** [comment]
히... 힘이 느껴진다!
