### ISSUE TITLE
릴리즈 멘토링 제도!

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#19]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  
#### 설명:

작년에 흐지부지되어 사라졌던 멘토링 제도!
다시 부활시킬 생각없으십니까?

멘토링이라는 제도에 대하여 다양한 의견이 듣고 싶습니다.
#### 확인:
- [x] **@JimJeon**
- [x] @chldlftjs

**Comment by juice500ml** [comment]
ㅠㅠ 저번에 멘토링 제도가 망한 이유는
- 사석에서 만나지를 않았다.
- 랩실에 신입생이 오지를 않았다.
- 릴리즈 친목활동이 전무했다.
- 랜덤으로 추천하는 활동을 좀더 기다려지는 활동이었으면... 한달 단위는 너무 긴 것 같아요 차라리 3일 단위로 막 돌려도 재미나보일듯

**Comment by JimJeon** [comment]
참고로 너가 내 멘토였습니다 ㅡㅡ

**Comment by JimJeon** [comment]
일선이 형이 합시다.

**Comment by minhoryang** [comment]
멘토링 제도가 무엇인가욥?

**Comment by chldlftjs** [comment]
@minhoryang 신입생들과 기존 릴리즈 회원들을 한 명씩 묶어서 멘토, 멘티의 관계로 친목을 다지려는 계획이었습니다. 근데, 광희가 언급한 이유들로 인해 망했던 제도입니다 ㅠ

**Comment by juice500ml** [comment]
@chldlftjs 멘토링 하나요?

**Comment by chldlftjs** [comment]
@juice500ml  이 멘토링 제도를 통해 릴리즈에서 얻으려는 것이 무엇이든 좋은 생각은 아닌 것 같아요. 친목이 주목적이면 차라리 acm-icpc에서 진행했던 '선배한테 커피 얻어먹기 이벤트' (후배가 선배들을 붙잡아서 커피를 얻어먹는 이벤트였습니다. 커피값은 학회에 청구하면 돈을 보내줬습니다.)와 같은 행사가 훨씬 나을 것 같아요.

**Comment by yunitto** [comment]
멘토링보단 차라리 #44 친목행사가 더 나을거같아요

**Comment by juice500ml** [comment]
@chldlftjs 만약 #44 가 멘토링보다 나아보인다면, 이건 추후에 필요성에 따라 다시 만들기로 하고, 이건 클로즈해주세요!
