### ISSUE TITLE
개총 준비

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/ReleaseWorld#2]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 #개총`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:   #3, #4, #6 
- **추천하고 싶은 사람**:  `최승환 (학회장)`
#### 설명:

개총이 다가오는데 무엇을 해야할까요?
#### 확인:
- [x] **@JimJeon**
- [x] **@tmdghks0612**

**Comment by tmdghks0612** [comment]
꺄옳 방금 만들고 있었는데에 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by juice500ml** [comment]
@minhoryang @tmdghks0612 
이슈 규칙

> 단 하나의 타입만 골라야 하고, 반드시 하나를 골라야 합니다.

**Comment by minhoryang** [comment]
@juice500ml @juice500ml @JimJeon  좋습니다! :)

**Comment by minhoryang** [comment]
수고하셨어요!!!!
