### ISSUE TITLE
한학기 세미나 준비를 해야합니다.

### ISSUE THREAD

**Issue by yunitto** [SGCSRelease/ReleaseWorld#20]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315 #신환회`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈: 
- **추천하고 싶은 사람**:  
#### 설명:

선배들 혹은 현업에 계신 분들을 초청해서 진로, 실무 얘기나 새로운 기술을 배우는 세미나를 계획합니다. 오늘 구글에 다니시는 선배님이 학교에 강연오셨는데 가능하면 한번 여쭤보도록 할게요!

<초청하고 싶은 분들>
1. 양민호 선배님 :) @minhoryang 
2. 최백준 선배님(백준 온라인 저지)
3. 교수님들은 어떨까요?
4. 네이버 (네이버는 강연을 나가는게 실적에 들어간다고 하니 거의 확정할 수 있을 것 같아요)

가능한 한 빨리 연락해서 일정을 잡는 게 공지하기도 편하고 더 많은 사람이 들을 수 있을거에요.
의견 부탁드려요!

**Comment by yunitto** [comment]
@juice500ml 작년엔 누가 오셨나요? 어떻게 일정을 잡았나요?

**Comment by minhoryang** [comment]
작년엔, 저+광희+재현횽+민후형(의료스타트업을 하시는 서강대 선배님)+...?
일정은 3일전쯤에, 주제와 같이 단톡방에 통보했어요.

**Comment by JimJeon** [comment]
이런 세미나를 했었습니다.
![newbinar poster](https://cloud.githubusercontent.com/assets/16199830/13777189/e1d57834-eaf1-11e5-9074-64b48a04c6f9.png)

**Comment by minhoryang** [comment]
### 올해 추천하고 싶은 세미나
- @juice500ml 의 Jr. Online Judge 개발기
- @jmg7173 의 AwesomeTitle 개발기
- @hubaimaster 의 세미나

**Comment by yunitto** [comment]
오 그러면 저 세미나는 릴리즈에서만 하는게 아니라 서강대생 전체를 대상으로 한 건가요?

**Comment by juice500ml** [comment]
@yunitto 그래도 매우 좋아보여용! 그리고 세미나 넘나 하고 싶은 것..!

**Comment by juice500ml** [comment]
그 당시에 아쉬웠던 점
- 홍보가 제때 이뤄지지 않아서 많은 사람들이 못왔음
- 맨 처음 너무 큰 곳에서 세미나를 진행해서 잘 들리지 않았음. 릴리즈 랩실에서 세미나하거나 그에 준하게 작은 곳에서 하는 게 좋아보여요.
- 사진찍던 사람이 없어서 기록에 제대로 남지 않았음
- 세미나 발표자료도 제대로 기록에 남지 않았음
- 신입생 대상이었는데 실제로 신입생은 별로 오지 않았음
- 실제로 신입생들에게 도움이 되었을까요? (본질적 질문)

**Comment by yunitto** [comment]
@juice500ml 당장에 직접적인 도움은 안되더라도 선배들을 보면서 미래를 꿈꿔보는 좋은 기회가 될거에요! 마지막 아쉬욷 점에 대한 제 의견입니당

**Comment by JimJeon** [comment]
그 당시에 들었던 신입생이 접니다!

민호형 세미나만 들었었는데,
그 때 "우리는 코더가 아닌 아키텍쳐가 되어야 한다"고 해주신 말씀이 아직도 기억에 남아요!

어떻게든 좋은 영향을 미치는건 맞는거 같아요!

**Comment by juice500ml** [comment]
제가 짚은 부분들을 체크리스트화해서 꼭 올해에는 되풀이되지 않도록 해주세요 화이팅입니당!
세미나는 누가 맡나요? @yunitto @JimJeon

**Comment by JimJeon** [comment]
세미나 관련한 일은 일선이형에게 맡기도록 하겠습니다.

**Comment by yunitto** [comment]
@JimJeon 세미나는 제가 맡을게요. 아무래도 제가 학번이 높으니 제가 연락하는게 더 수월할 것 같아요. 오늘 **이혜민** 구글 선배님도 제가 컨택했으니 제가 맡을게요!!! 신난다!!!

**Comment by juice500ml** [comment]
우와ㅏ아아ㅏ 구글선뱃님! 수고하셨어요!!! 이 기쁨을 민호형에게도 @minhoryang

**Comment by yunitto** [comment]
@juice500ml 컨택도 민호선배님이 다 해주셨습니다ㅠㅠㅠ 짱짱bbb

**Comment by juice500ml** [comment]
:+1: \* INT_MAX for @minhoryang

**Comment by minhoryang** [comment]
제가 다음주 화요일날 하루 일해주는걸로.... 등가(?!)교환을

**Comment by minhoryang** [comment]
여기 검색되는곳이에요. 성함은 꼭 챙겨서 써주세요^^

**Comment by juice500ml** [comment]
@yunitto 얼마나 진행되고있나요? 만약 이 이슈 대신 release day 이슈로 넘기려면 클로즈해주세용!

**Comment by yunitto** [comment]
@juice500ml 이건 한학기 세미나를 계획하는 이슈라서 조금 오래 열어뒀습니다ㅜㅠ 최종 세미나 라인업 결정해서 다시 올리겠습니다
