### ISSUE TITLE
Issue #13 이 너무 방대해지는 중입니다.

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#21]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @JimJeon 
#### 설명:

Issue #13 이 주제에 맞지 않은 문제를 해결하려 하고 있네요!
Issue close 해주시고 새로운 Issue로 오픈해주세요!
#### 확인:
- [x] **@JimJeon**

**Comment by JimJeon** [comment]
ㅂㄷ
