### ISSUE TITLE
회칙을 옮겨라!

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#22]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈:   #13 
  - 자식 이슈:  
- **추천하고 싶은 사람**:  
#### 설명:

깃으로 릴리즈 회칙을 옮깁시다.
#### 확인:
- [x] **@JimJeon**
- [ ] @charcoalbug

**Comment by JimJeon** [comment]
윤영이랑 할께요

**Comment by minhoryang** [comment]
2191d23d45a191a7f3028ef516a5091d9bbc84ca 여기에 올렸어요!
