### ISSUE TITLE
빨리 완료하여야 합니다 이슈의 기준이 뭔가요?

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#23]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160320`
- **관련된 이슈들**:
  - 부모 이슈:   `null`
  - 자식 이슈:   `null`
- **추천하고 싶은 사람**:  @JimJeon 
#### 설명:

기준을 정하는게 좋을 듯 합니다. 24시간, 48시간, 72시간 등...
#### 확인:
- [x] **@JimJeon**

**Comment by JimJeon** [comment]
24시간 전으로 하면 좋을 듯 합니다!

**Comment by JimJeon** [comment]
이에 대한 찬성과 반대의견을 들려주셨으면 합니다.

**Comment by juice500ml** [comment]
그러면 `빨리 완료해야 합니다` 대신 `24시간 내로 완료해야 합니다!`가 좋을꺼같아요

**Comment by JimJeon** [comment]
최택
