### ISSUE TITLE
우리도 진행상황을 알고 싶어요!

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#24]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  ``
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @모두모두
#### 설명:

issue관련한 일들이 어떻게 진행되어 가는지 알고 싶어요!
논의를 GitHub를 이용해서 해주셨으면 합니다!
그게 힘들면 적어도 무언가 이야기가 오고 간 후에 그 내용을 적어서 올려주셨으면 해요!
안 그러면 도와주거나 다른 일들을 처리하기가 힘들어요!
#### 확인:
- [x] **@JimJeon**

**Comment by minhoryang** [comment]
+1

**Comment by chldlftjs** [comment]
+1

**Comment by juice500ml** [comment]
:+1:

**Comment by jmg7173** [comment]
@tmdghks0612 깃허브에 자주자주 comment나 issue를 날려주세요!

**Comment by JimJeon** [comment]
@charcoalbug 깃허브에 자주자주 comment나 issue를 날려주세요!

**Comment by JimJeon** [comment]
이거 닫을께요 ㅋㅋ
