### ISSUE TITLE
ReleaseDay는 언제 진행되나요?

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#25]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈:   #(이슈 번호)
  - 자식 이슈:   #(이슈 번호), ...
- **추천하고 싶은 사람**:  최승환 @tmdghks0612
#### 설명:

3/16일 개총 회의에서 매달 마지막 주 토요일 2시에 진행하기로 결정했습니다!
차후 세미나 내용은 댓글을 통해 알려드리겠습니다!
#### 확인:
- [x] @tmdghks0612

**Comment by minhoryang** [comment]
@JimJeon 릴리즈 데이 마일스톤에 이번달 마지막주 토요일 2시에 진행하는 걸로 날짜 설정해주시고
@tmdghks0612 이건 닫아도 되겠죠?

**Comment by JimJeon** [comment]
닫겟습니다.
