### ISSUE TITLE
스터디는 어떻게 진행할까요?

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#26]
- [x] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**: 
- **관련된 이슈들**:
  - 부모 이슈:   #(이슈 번호)
  - 자식 이슈:   #(이슈 번호), ...
- **스터디를 맡아줄 사람**: @jmg7173 @tmdghks0612 
#### 설명:

스터디는 선호도는 JAVA 및 Android 스터디가 가장 수요가 높지만, 다른 스터디도 진행하고 싶어하는 사람들이 있어서 다른 스터디도 진행하고자 합니다. 각 스터디별로 사람을 모아서 진행하고싶은 날짜를 정해봅시다! 
진행가능하고 수요가 있는 스터디 : 
- Python
- Java
  - Android 포함
- Swift(IOS앱 개발)
#### 확인:
- [x] @jmg7173
- [x] 학회원 모두!

**Comment by minhoryang** [comment]
+1 "스터디를 맡아줄 사람: @jmg7173 @tmdghks0612" 엌ㅋㅋㅋㅋ

**Comment by juice500ml** [comment]
진행 가능 여부가 아니라 수요부터 조사해야하는 건 아닌가요?
진행 가능 여부의 경우 Swift는 진행이 가능한가요?
수요 조사를 할 때에 별다른 선택권을 제시하지 않으신거려나요
Issue #8 에 올린 제 댓글을 다시 갖고오자면, 

> 언어 기준(C, Python, Java ... )
> 만드는 것 기준(Mobile app, Web service, Game development ...)
> 주제 기준(Github, Programming Style, Design Pattern ...)
> 기준은 많을 수 있어요! 굳이 C/Python으로 고민하지 않으면 좋겠어요.
> 덧붙이자면, 꼭 학번을 구분하지 않고 스터디를 했으면! 16도 스터디의 주체가 되어도 좋아요!

**Comment by tmdghks0612** [comment]
스터디를 맡아줄 사람이 정해져서 써놓거나 한 것이 아니라 회의에서 수요조사한 결과를 기록해둔 거에요
위에 써두기도 했지만 만드는 것을 기준으로(안드로이드 앱 쪽 하고 싶다는 분이 가장 많았음) JAVA & 안드로이드가 가장 많았고 그 다음이 Swift(IOS) 였다는 거에요 모바일 앱을 개발하고 싶은 사람들이 많았다고 할 수 있을 것 같아요

**Comment by juice500ml** [comment]
스터디 진행은 어떤 식으로 하는걸 생각중인가요?

**Comment by juice500ml** [comment]
그리고 위에 말은 수요조사가 객관식이 아니라 주관식으로 진행되었어야했다고 생각했는데!

**Comment by juice500ml** [comment]
@tmdghks0612 이건 어떻게 진행되고있나요? 릴리즈데이로 넘어갔으면 클로즈해주세요

**Comment by tmdghks0612** [comment]
스터디 관해서는 하고 싶은 스터디 여러 개를 동시에 진행하고 시간 되는 사람끼리 하자는 의견도 있고 한두개만 진행하자는 의견도 있고 해서 이것부터 결정되어야 진행방식이 결정되겠죠. 그래서 릴리즈데이로 넘어가는게 맞는 것 같아요. 
@JimJeon 클로즈 해주세요
그리고 저번에 수요조사도 객관식으로 하고 추가하고 싶은 것 있으면 추가해달라는 식으로 했는데 의견이 거의 안 나왔어요. 이번에 수요조사를 하면 잘 될지 모르겠네요. 없으면 기존에 정해뒀던 것들을 선택지로 주는 게 맞는 것 같아요.
