### ISSUE TITLE
사물함 열쇠를 찾아주세요!

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#27]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160326 #3월_릴리즈데이`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @chldlftjs @charcoalbug 
#### 설명:

4번이랑 21번 사물함 열쇠를 기존 사용자분들로부터 오늘 받았어요

아직 사물함 열쇠 8번 10번 12번 14번 15번 이 없습니다.

이 분들 열쇠는 연락드리거나 해서 열쇠가 복사가 필요한 경우는 복사해서 열쇠함에 구비해뒀으면 좋겠어요
#### 확인:
- [x] **@JimJeon**
- [x] @charcoalbug

**Comment by tmdghks0612** [comment]
17번 열쇠 찾아서 목록에서 지웠어요!

**Comment by minhoryang** [comment]
에!???!? 제가 12번이었을테고, 그건 어제 드렸던걸로 기억하는데요?!

**Comment by JimJeon** [comment]
얼마나 진행되었나요?
12번 민호형께서 주신 열쇠는 찾은간가요?
다른 열쇠는 찾고 있나요?
진행상황을 알고싶어요!

**Comment by charcoalbug** [comment]
따로 연락은 드려본건가요?

**Comment by JimJeon** [comment]
@charcoalbug 너가 하세요 너가 하는 일이잖아요

**Comment by juice500ml** [comment]
이 이슈 왜 클로즈 안되어있나요? 레이블이 24시간 내로 완료해야함. 인데요? @charcoalbug @JimJeon
