### ISSUE TITLE
MT 갈지말지/일정을 결정해요

### ISSUE THREAD

**Issue by yunitto** [SGCSRelease/ReleaseWorld#28]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `이번주 내로`
- **관련된 이슈들**:
  - 부모 이슈:
  - 자식 이슈:
- **추천하고 싶은 사람**:  @tmdghks0612 
#### 설명:

엠티는 3월 내로 가야하지않을까요? 4월엔 중간고사때문에 바빠질테니까요. 만약 엠티 일정을 잡기가 힘들다면 봄소풍 일정이라도 확정해야 거기에 개인 일정들을 맞출 수 있겠죠?

일단 엠티를 갈지말지부터 정해요~
#### 확인:
- [x] @JimJeon
- [x] @tmdghks0612 
- [x] @charcoalbug 
- [x] @jmg7173 
- [x] @chldlftjs

**Comment by chldlftjs** [comment]
전 여름방학에 가는 게 좋다고 생각합니다

**Comment by fuzzythecat** [comment]
여름방학에 가는게 좋을 것 같아요!

**Comment by tmdghks0612** [comment]
엠티는 여름이 좋을 것 같긴 한데 벚꽃축제 기간에 하루 정도 같이 가볍게 놀러가는 게 좋을 것 같아요
벚꽃축제는 3월말이나 4월초로 알고 있어요

**Comment by charcoalbug** [comment]
저도 mt는 여름 방학때 가고, 가볍게 놀러 가는 거는 4월 초 쯤이 좋다고 생각 합니다.

**Comment by JimJeon** [comment]
벚꽃이 피면 간단하게 한강으로 소풍을 가고
중간고사가 끝나면 엠티를 한 번 가는거도 좋을 거 같아요.
그리고 여름방학 때는 재밌게 놀러 갑시다!

**Comment by jmg7173** [comment]
엠티는 방학때! 소풍은 중간고사 전후에!

**Comment by yunitto** [comment]
@JimJeon @tmdghks0612 @charcoalbug @jmg7173 @chldlftjs  소풍 이슈 새로 오픈할까요?

**Comment by JimJeon** [comment]
여기서 선택지를 추려서 객관식으로 만들어보고 새 이슈를 열어서 그 중에 골라보죠

(1학기 기준)

#### 횟수에 관한 결정
- 소풍 1번 엠티 1번
- 그 이상

#### 일정에 관한 결정(소풍)
- 4월 초 벚꽃이 필 무렵
- 4월 중순에서 말 중간고사가 끝나고 나서
- 안 가요

#### 일정에 관한 결정(엠티)
- 4월 말 중간고사가 끝나고 나서
- 6월 넘어서! 기말고사 끝나고 방학 (여름이다!)
- 안 가요

이런식으로 하면 되지 않을까요?

**Comment by juice500ml** [comment]
이 결정은 릴리즈데이때로 넘기는건 어떻게 생각하시나요?

**Comment by yunitto** [comment]
넵 릴리즈데이때 해도 좋을 것 같아요! 다른 회원분들 의견도 들어보고 결정해야할것 같아요. 그럼 릴리즈데이 계획 전용 이슈 오픈하고 이건 닫겠습니다.
