### ISSUE TITLE
관리시간표를 작성중이에요

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/ReleaseWorld#29]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160319 다음주 전까지!`
- **관련된 이슈들**: #14 (릴리즈 명단)
  - 부모 이슈:
- **추천하고 싶은 사람**:  어제 DB정보를 얻어간 @jmg7173 와, 이 프로그램을 만든 @juice500ml @taeguk 
#### 설명:

사실 우리에게는 관리시간표를 짜주는 프로그램이 있었어요! https://github.com/SGCSRelease/lab_management
이걸로 관리시간표를 짜보려고 노력중이에욧!
#### 확인:
- [x] **@JimJeon**
- [ ] @jmg7173 
- [ ] @juice500ml 
- [ ] @taeguk

**Comment by minhoryang** [comment]
1. .104 phpmyadmin 접속한다음
2. `apply_list`와 `user_list` 테이블만 `내보내기` 탭을 클릭해서
3. CSV로 내보내기 + `커스텀` 옵션 (**"첫 줄에 열 이름을 넣기" 체크**)
4. python3 terrible_export.py

**Comment by minhoryang** [comment]
- **아직 우선순위를 다 채우지 않으신 분들**:
  - 16이O진
  - 16박서O
- **아직 답변을 안하신 분들**:
  - ~~15최O선~~ -- 부학회장
  - ~~15박경O~~ -- 컴과가 아니고
  - ~~16박O현~~  -- 14휴학
  - 16안향O

**Comment by taeguk** [comment]
아 맞다..
https://github.com/SGCSRelease/lab_management/blob/master/release_manage_website/export_db_to_input.php
에 db를 광희가 짠 알고리즘의 input에 맞게 export하는 스크립트가 있어요...ㅠㅠ
$ php export_db_to_input.php
이렇게 실행하면 되요 ㅠㅠㅠ

**Comment by minhoryang** [comment]
@taeguk 그거 제가 만들었는데...terrible_export라고... 한번 확인해주시겠어요ㅠㅠ

**Comment by minhoryang** [comment]
제 것이 문제가 있는듯. 태국이껄로 돌릴게요.

**Comment by minhoryang** [comment]
읔. 태국이것도 문제가 있네욧.;ㅅ;

**Comment by yunitto** [comment]
@minhoryang 16에는 박O현 이라는 분이 없어요! 제가 아는 이름이 맞다면 14인데 지금 휴학하셔서 관리를 안들어간다고 알고있어요. @juice500ml 맞나요?

**Comment by taeguk** [comment]
@yunitto 맞아요 14학번이고, 이번에 들어왔는데 휴학생이세요.

**Comment by taeguk** [comment]
@minhoryang 엇...그럴리가... 저번 학기에는 잘 됐는데 ㅠㅠㅠㅜㅠ

**Comment by minhoryang** [comment]
14김O우 씨가 3개 신청했는데...... 수요일 4/5교시와 금요일 5교시 된다고 하네요. 기억해둘게요.

**Comment by minhoryang** [comment]
@taeguk 돌려랏!

**Comment by minhoryang** [comment]
@yunitto 명단 업데이트 해주세욧! DB에서는 지울게욧!

**Comment by taeguk** [comment]
@minhoryang 음 제가 짠거는 단순히 db에 정보를 저장하고 그걸 export해주는 것 뿐이라... 혹시 알고리즘에 문제가 있는건 아닐까요?? @juice500ml

**Comment by minhoryang** [comment]
버그를 픽스했어욧.

@taeguk 알고리즘에서 임포트하는 서식이 바뀌었더라구요. ^^

**Comment by minhoryang** [comment]
저 약속가야해서;;;;
릴리즈 서버에 lab_management_assignment.py를 돌리고 있는데요.
다 돌아가면 https://gist.github.com/minhoryang 여기에 최 상단에 뜰거에욧;
누군가 릴리즈 서버를 htop으로 지켜보다가, 다 되면 저에게 푸시좀요!

**Comment by charcoalbug** [comment]
다음주 월요일 까지는 정식 관리 시간표를 만들었으면 해요. 그래서 만약 이번주 금요일 까지 정상적으로 작동이 안될 경우 토요일 부터 수동 으로 관리 시간을 받아도 될까요? 톡방에 관리 시간표 링크를 뛰우는 방식으로요.

**Comment by minhoryang** [comment]
https://gist.github.com/minhoryang/370223f95df4ed2d627f (결과가 짤렸어요 ㅠㅠ)

@charcoalbug 당연하죠! 그 전에 안되면 기존에 되어있는 걸로 시트도 만들어볼게요

**Comment by chldlftjs** [comment]
신청 안 한 분들 중에 '15최일선'은 일단 임원이라 신청대상이 아닙니다.

**Comment by minhoryang** [comment]
넵! 빼겠습니다.

**Comment by minhoryang** [comment]
결론이 잘 안나요;ㅅ;ㅠㅠ

**Comment by minhoryang** [comment]
mon 2교시 가 5개 신청되었습니다.
mon 3교시 가 5개 신청되었습니다.
mon 4교시 가 4개 신청되었습니다.
mon 5교시 가 6개 신청되었습니다.
mon 6교시 가 10개 신청되었습니다.
mon 7교시 가 7개 신청되었습니다.
tue 2교시 가 5개 신청되었습니다.
tue 3교시 가 3개 신청되었습니다.
tue 4교시 가 2개 신청되었습니다.
tue 5교시 가 4개 신청되었습니다.
tue 6교시 가 8개 신청되었습니다.
tue 7교시 가 6개 신청되었습니다.
wed 2교시 가 4개 신청되었습니다.
wed 3교시 가 5개 신청되었습니다.
wed 4교시 가 6개 신청되었습니다.
wed 5교시 가 9개 신청되었습니다.
wed 6교시 가 7개 신청되었습니다.
wed 7교시 가 4개 신청되었습니다.
thu 2교시 가 6개 신청되었습니다.
thu 3교시 가 5개 신청되었습니다.
thu 4교시 가 5개 신청되었습니다.
thu 5교시 가 6개 신청되었습니다.
thu 6교시 가 10개 신청되었습니다.
thu 7교시 가 8개 신청되었습니다.
fri 2교시 가 7개 신청되었습니다.
fri 3교시 가 6개 신청되었습니다.
fri 4교시 가 7개 신청되었습니다.
fri 5교시 가 7개 신청되었습니다.
fri 6교시 가 9개 신청되었습니다.
fri 7교시 가 8개 신청되었습니다.

**Comment by minhoryang** [comment]
https://docs.google.com/spreadsheets/d/1coh1ujm0rzkPrS8_QcIL3WSsxpTU80KvHVdYnryQGHI/edit?usp=sharing

**Comment by minhoryang** [comment]
익명의 기린 누구세요~

**Comment by taeguk** [comment]
@minhoryang 저옄ㅋㅋㅋㅋㅋㅋㅋ

**Comment by minhoryang** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ :)

**Comment by minhoryang** [comment]
지금 잠깐 봐주시겠어요?!?ㅠㅠ

**Comment by minhoryang** [comment]
**금요일날 7교시에 가능한 분이 아무도 없습니다! ㅠㅠㅠㅠ**

**Comment by minhoryang** [comment]
어? 금7빼고는 관리시간이 완성되었는데요?ㄷㄷㄷ

**Comment by minhoryang** [comment]
**결과가 완성되었습니다!**

**Comment by JimJeon** [comment]
와아! 금 7은 어떻게 되는건가요? 제가 컴실이 있긴 한데 만약 정 넣을 사람이 없으면 저를 넣어주세요!

**Comment by JimJeon** [comment]
흠.... 컴실이 있으면 못하는구나..ㅠ

**Comment by minhoryang** [comment]
![2016-03-18 12 33 06](https://cloud.githubusercontent.com/assets/1270855/13851357/2bda8860-eca1-11e5-82a3-06660f4aae21.png)

**Comment by minhoryang** [comment]
학회장에게 전달했습니다!
