### ISSUE TITLE
개강총회_피피티

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#3]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈: 개총 준비 #2
  - 자식 이슈: 
- **추천하고 싶은 사람**:  `최승환, @tmdghks0612`
#### 설명:

개강총회에 필요한 발표자료를 만들어요!
#### 확인:
- [x] **@JimJeon**
- [x] **@tmdghks0612**

**Comment by yunitto** [comment]
피피티 다 만든 후에 공유해주세요~ :)

**Comment by JimJeon** [comment]
@tmdghks0612 our time is running out

**Comment by jmg7173** [comment]
개총 발표 잘 끝났습니다!

**Comment by minhoryang** [comment]
PPT 구글 드라이브 링크 올려주세요!

**Comment by yunitto** [comment]
[개강총회 PPT](https://docs.google.com/presentation/d/1hGJGOb6RLpnJtoqmE36sWyiQ_xTeyKYiXy2NB1vRtLY/edit?usp=sharing)

**Comment by minhoryang** [comment]
@yunitto 올려주셔서 감사해욧. 그런데 모든사람에게 열려있는 것 같은데, 16그룹원만 볼 수 있도록 줄여주시겠어요?
