### ISSUE TITLE
릴리즈 서버 신청해야죠! 관리장이 혹시 있나용?

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/ReleaseWorld#30]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315 #릴리즈데이1`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  ?!
#### 설명:

Git세미나 할 때도 필요하구요, 후배들에게 서버의 아이디를 제공해 줘야 할 것 같아요!
#### 확인:
- [x] **@JimJeon**
- [ ] @Assignee

**Comment by JimJeon** [comment]
이번에 관리장을 없애고 전부 '임원진'으로 만들어버렸어요!

**Comment by taeguk** [comment]
Worker Thread Poooooool?!

**Comment by minhoryang** [comment]
그렇죠?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그러면어떻게할까요!

**Comment by jmg7173** [comment]
root권한이 있는 계정을 가진 분이 민호형 제외하고 누구누구있나요?

**Comment by minhoryang** [comment]
- voidness(11김D현),
- hduser(??!)
- releaseweb(릴리즈홈페이지)
- minhoryang(09양민H, 메리버드용)
- zeroOne(10?!?)
- sbj009(09손B진)
- angryonhim(09양M호,실사용),
- juice500(14최G희)

**Comment by minhoryang** [comment]
어쨋든 신입 sudoer가 필요하네요 손?

**Comment by JimJeon** [comment]
앞발!

**Comment by JimJeon** [comment]
저 슈퍼해지고 싶어요!

**Comment by jmg7173** [comment]
이로써 짐전은 두개의 sudoer가 되는건가..!

**Comment by juice500ml** [comment]
@JimJeon sudo 받았나요?

**Comment by minhoryang** [comment]
아직 못줬어용; 릴리즈데이전에 해결할게욧!

**Comment by JimJeon** [comment]
제 계정은 irreg***\* 입니다

**Comment by JimJeon** [comment]
아.. 음.. 그냥 톡으로 얘기드리겠습니다!

**Comment by minhoryang** [comment]
카톡방이 생겼구요. 조만간 서버용 리파지토리를 파서 돌아오겠습니다!
