### ISSUE TITLE
Release회원분들 SGCSRelease그룹 초대 현황을 알고싶습니다!

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#31]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈:   X
  - 자식 이슈:   #32 
- **추천하고 싶은 사람**:  @tmdghks0612 @JimJeon 
#### 설명:

현재 SGCSRelase 그룹에 초대가 얼마나 되어있나요? 현황 좀 알려주시겠나요!!
#### 확인:
- [x] **@tmdghks0612**
- [x] **@JimJeon**

**Comment by JimJeon** [comment]
흠... 명단을 올려 체크하려 했으나 생각해보니 개인정보보호 차원에서 현재 얼마나 진행되었는지 진행률로 표시해드리도록 하겠습니다.

총 활성회원 31명 중 15명이 가입했습니다.
[===============--------------------------]48%

**Comment by minhoryang** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by taeguk** [comment]
이거 어떻게 가입해요?

**Comment by JimJeon** [comment]
@taeguk 가입되어 있습니다!!!

**Comment by juice500ml** [comment]
@tmdghks0612 Release회원분들 SGCSRelease그룹 초대 현황을 알고싶습니다!

**Comment by yunitto** [comment]
@tmdghks0612 명단 대조하고 정리해서 활성회원 중 아직 초대안된 사람은 낮 12시 전까지 단톡방에 공지해주세요

**Comment by JimJeon** [comment]
총 33명 github 가입완료
[=================================]100%
