### ISSUE TITLE
Release 회원분들이 ReleaseWorld에 올라오는 이슈들을 보고있는지 궁금합니다!

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#32]
- [x] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈:  #31 
  - 자식 이슈:  X
- **추천하고 싶은 사람**:  학회원 모두!
#### 설명:

Release 학회에 계신 학회원분들!
Github의 SGCSRelease에 초대되어 issue에 comment를 달 수 있다면 ReleaseWorld를 보고 있다고 외쳐주세요!

**Comment by juice500ml** [comment]
외쳐! EE!

**Comment by JimJeon** [comment]
외쳐! EE!

**Comment by jmg7173** [comment]
외쳐 RW!

**Comment by dbdydgur2244** [comment]
왜쳐?!

**Comment by taeguk** [comment]
전 깃헙이 재밌어서 다 읽고 있긴한데 너무 많아요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by chldlftjs** [comment]
EE!

**Comment by raon0211** [comment]
보고 있어요ㅋㅋ

**Comment by diana917** [comment]
메일로 다 와서 하나씩 다 읽어봤어요!
