### ISSUE TITLE
아이디만 보고 누가 누군지 모르겠어요!

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#33]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160320 일요일 전까지 완료하고 싶어요!`
- **관련된 이슈들**:
  - 부모 이슈:   #31 
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @tmdghks0612 @chldlftjs @charcoalbug 
#### 설명:

현재 초대된 사람이 23명
초대 승낙 대기중인 사람이 3명
앞으로 초대해야 하는 사람이 5명

그런데 누가 초대된거고 누가 초대되지 않은건지 모르겠어요.
조사를 부탁드립니다.....
#### 확인:
- [x] **@JimJeon**
- [ ] @charcoalbug

**Comment by JimJeon** [comment]
@charcoalbug 에게 맡기겠습니다!

**Comment by minhoryang** [comment]
AwesomeTitle!!!!!!!!

**Comment by JimJeon** [comment]
멋진제목!!!!!
멋진제목을 이용하시란 말씀이신가요?????

**Comment by minhoryang** [comment]
AwesomeTitle의 기능으로 검색하면 되잖아요!

**Comment by JimJeon** [comment]
흐어! 아직 멋진제목에 깃헙 아이디가 구현되지 않아서요.. ㅠ
우선은 활성회원들을 가입시키기 위해 조사가 필요합니다!
그래서 공지올리고 다들 가입 시키는중입니다!

**Comment by jmg7173** [comment]
@JimJeon 죄송 ㅠㅜ 아직 외부아이디기능을 못만들어서 흑..

**Comment by JimJeon** [comment]
아님다.. ㅋㅋ sp화이팅하세요!

**Comment by juice500ml** [comment]
@JimJeon 다들 가입 되었나요?

**Comment by mandoriiiii** [comment]
아이디와 학번 이름을 문서화하는 건 어떨까요

**Comment by juice500ml** [comment]
#31 과 함께 처리해주세요!

**Comment by JimJeon** [comment]
초대 완료되었습니다
이 아이디들은 멋진제목에 추후 추가하는걸로...

**Comment by juice500ml** [comment]
@charcoalbug 이거 드라이브에 정리되고 있는건가요?

**Comment by JimJeon** [comment]
드라이브에 정리해서 올리도록 하겠습니다.

**Comment by JimJeon** [comment]
정리해서 드라이브 올리는 것까지 완료했습니다.
