### ISSUE TITLE
관리 시간표에 문제가 없는지 확인해주세요!

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#34]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160320`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  정민교 @jmg7173
#### 설명:

관리 시간표가 완성됐어요. 링크는
https://goo.gl/Cn9fXk
----시트3에 있어요!-----
혹시 문제가 있는지 확인해주세요. 문제 없으면 공지하려고 해요.
#### 확인:
- [x] **@jmg7173@**

**Comment by jmg7173** [comment]
없는것 같군요!
issue close할게요

**Comment by yunitto** [comment]
저녁관리도 2시간인만큼 관리자가 저녁식사를 할 시간이 필요하다는 의견이 나왔습니다. 저녁에는 랩실에 항상 사람이 많으니 관리자가 랩실에 있는 사람에게 양해를 구하고 저녁을 먹고 오기로 정했습니다. 강제가 아니기 때문에 추후에 불편함이 생기면 임원진이 추가적으로 들어가는 등의 대안을 적용하도록 하겠습니다.
