### ISSUE TITLE
학회원 여러분의 구글 아이디가 필요해요!

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#35]
- [x] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [x] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  학회원 전체
#### 설명:

Release의 활동들을 여러분과 공유해 쉽게 문서들을 볼 수 있도록 하려합니다!
그런데 회계 내역 같은 것들은 외부인들에게 공개 하기가 좀 그렇죠? 그래서 외부인들에게 공개가 제한되는 문서들을 학회 내에서 공유하기 위해서는 구글 아이디가 있어야 특정 사용자들 에게만 공유가 가능해요. 그래서 밑에 있는 구글설문지 링크에 여러분의 구글아이디를 적어주셨으면 좋겠어요!
https://goo.gl/ab5zo0

**Comment by sjlee2016** [comment]
아이디: sjleesogang@gmail.com
이름: 이세진

**Comment by diana917** [comment]
dayeonjeong917@gmail.com 입니다!

**Comment by gomamon** [comment]
leeye9779@gmail.com
이예은 입니다~!

**Comment by dhdh6190** [comment]
아이디 : dhdh6190@gmail.com
이름 : 김도현

**Comment by 20151571** [comment]
이메일:
dbdydgur2244@gmail.com
이름 : 유용혁 입네다

**Comment by jmg7173** [comment]
여기 대신 구글설문지에 옮겨주세요 ㅠㅠ 이미 쓰신 분은 안옮기셔도 됩니다
https://goo.gl/ab5zo0

**Comment by taeguk** [comment]
권태국 xornrbboy@gmail.com

**Comment by JimJeon** [comment]
여기는 우리 뿐만 아니라 모든 사람들에게 오픈된 공간이에요...
그래서 여기에 이름과 이메일을 쓰면 개인정보보안이 좀...;;;
이미 쓰신 분들도 comment 삭제하고 드라이브로 옮기는게 좋지 않을까요?
@jmg7173

**Comment by jmg7173** [comment]
아 드라이브로는 옮겼는데 삭제하는 걸 생각을 못했네요 삭제할게요!는 이미 되있네

**Comment by yunitto** [comment]
@tmdghks0612 지금까지 몇명 제출했나요? 제출 안한사람 명단 추려서 단톡방에 공지해주세요.

**Comment by yunitto** [comment]
다 받았으니 이슈 클로즈할게요!

**Comment by jmg7173** [comment]
아이디도 다 받았고 공유도 완료했습니다!
