### ISSUE TITLE
3/26 (토) 첫 릴리즈데이를 준비해요 :)

### ISSUE THREAD

**Issue by yunitto** [SGCSRelease/ReleaseWorld#36]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160326 릴리즈데이`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈: C언어 스터디 #39, 단체티 논의 #41, 친목행사 #44 
- **추천하고 싶은 사람**: 
#### 설명:

2시-3시 : 
(1) 사물함 배정 확정
(2) C언어 스터디 논의 #39
(3) 단체티 논의 #41
(4) 조별 깃헙 이슈 오픈해보기 #40 

3시-4시 : 깃허브 세미나( @minhoryang )

4시-5시 : Python 세미나 ( @juice500ml  )

이후 뒷풀이~
#### 확인:
- [ ] @minhoryang 
- [ ] @juice500ml 
- [x] @tmdghks0612

**Comment by yunitto** [comment]
단체티 맞추는 것도 토요일 2~3시 사이에 얘기하면 어떨까요? @tmdghks0612

**Comment by minhoryang** [comment]
[제가 예전에 좋은 바탕화면 만들어 놓았어요](http://r.reluv.me/fTZk)

**Comment by juice500ml** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ저겈ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by juice500ml** [comment]
![464463_1](https://cloud.githubusercontent.com/assets/7028312/13940987/36ff3b68-f026-11e5-9836-7f99ad0b0c54.jpg)

고전짤 등장

**Comment by juice500ml** [comment]
@yunitto @minhoryang 파이썬 세미나를 한시간만에 끝낼 수 있으려나..ㅠㅠ 잘 모르겠네요 협의가 필요할 것 같은데요!

**Comment by charcoalbug** [comment]
행정업무 관련 시간 에는 어떤걸 하나요. 관리키만 배부하는 거라면 그때 시간을 줄여서 세미나 시간을 늘릴 수 없을까요?

**Comment by juice500ml** [comment]
@yunitto @tmdghks0612 단체티 맞추는거 한 세 개 정도 후보를 만들어놓고 고르는게 나을 것 같아요

**Comment by juice500ml** [comment]
@charcoalbug 지각생들때문에 그런것같기도 하고. 단체티도 해야 할 것 같구요. @chldlftjs 다같이 협의 하셔서 해야 할 행정업무 리스트로 정리해주실래요?

**Comment by tmdghks0612** [comment]
2시에서 3시 사이에는
1.사물함 배정받은 분들 중에 열쇠 안 받으신 분들 열쇠 배분
2.스터디에 관해 더 들을 의견(c 스터디 할 의향, 이외에 진행했으면 하는 스터디)
3.단체티(같이 봐 둔 디자인들 좀 있어요) 의견 - 옷 종류, 디자인, 색상, 수요
4.봄소풍 계획 및 인원조사
이 정도로 보고 있어요.
그리고 전자과 분 세미나는 3시에 진행하는 걸로 되어 있어요

**Comment by minhoryang** [comment]
@tmdghks0612 아 굿잡굿잡. 그런데 전자과분이 세미나를 해주신다구욧?! 주제가...

**Comment by minhoryang** [comment]
끝나는 시간을 안정해서, 세미나가 길어 저도 될 거에요. 근데.... 하는 사람이 버틸 수 있냐는 다른 문제..

**Comment by juice500ml** [comment]
@tmdghks0612 전자과분 세미나 내용 등 릴리즈데이때 무슨 일을 할 지 픽스되면 카톡방에 공지해주세요!

**Comment by tmdghks0612** [comment]
네! 내용 더 자세히 여쭤봤으니까 수업 끝나고 확인하고 시간 좀 조정해서 공지방 올릴게요

**Comment by tmdghks0612** [comment]
3시에 예정이었던 11학번 전자공학과 분 세미나 취소하셨어요.

**Comment by tmdghks0612** [comment]
깃허브랑 python세미나 일정을 3시로 당기는게 괜찮을까요? @juice500ml @minhoryang

**Comment by juice500ml** [comment]
일정이 픽스되면 괜찮아요. 확실히 픽스해서 공지해주세용!

**Comment by juice500ml** [comment]
#44 도 이 이슈의 자식이슈로 하면 어떨까요? 릴리즈데이 기점으로 기획 픽스해서 공지하면 좋아보여요!
@tmdghks0612 @yunitto

**Comment by tmdghks0612** [comment]
일정 공지해뒀어요!
다음과 같습니다.
2:00 시작
-사물함 배분
-스터디 안내
-단체티 디자인 수요조사
-봄소풍 공지
3:00 github 세미나(by 양민호)
4:00 python을 이용한 웹 세미나(by 최광희)

필요한 스터디가 있으면 깃허브를 통해 올려달라고 얘기했어요.

그리고 정기모임이라 공식적인 뒷풀이는 갖지 않으려고 합니다.

**Comment by taeguk** [comment]
ㅠㅠ 그래두 3시간이상 있는 건데 뒤풀이 하는게 좋지 않을까요?? ㅠㅠ

**Comment by honamgyu** [comment]
객관적으로 봐도 그거 인정...

**Comment by yunitto** [comment]
공식적인 뒷풀이란 학회에서 지원해주는 것을 말합니다. 재정상황이 모든 뒷풀이를 지원해줄 만큼 넉넉하진 않아서 릴리즈데이를 지원하긴 힘들것 같아요. 그 대신 아마 개인적으로 돈을 조금씩 모아서 갈듯해요~

**Comment by taeguk** [comment]
@yunitto 아아 그런거라면 찬성!!

**Comment by yunitto** [comment]
<봄소풍 결정 사항>
봄 소풍은 4월초, 4월말에 모두 가기로 함.
4월초는 즉흥적으로, 4월말에는 날짜를 정해서 가기로 했어요.
그런데 4월말에 총엠이랑 뻔엠이 있는데 아직 날짜가 정해지지 않아서 그 두 행사 날짜가 정해진 후에 봄소풍 일정을 확정하기로 해요! (단톡방 투표)

**Comment by yunitto** [comment]
<단체티 결정사항>
단체티받아욧 #51에서 가장 많은 (좋아요수-싫어요수) 를 받은 후보군 3개와 좀더 찾은 후에 5개정도를 추려서 단톡방에서 투표하기로 했어요.

**Comment by yunitto** [comment]
<스터디 결정사항>
C스터디 인원
최일X, 이세X, 정다X, 유용X, 박서X, 이예X, 김형X, 전진X, 최승X

JAVA
전진X, 이예X, 이세X, 정다X, 이상X, 최윤X, 박태X, 신인X, 허남X, 유용X, 최승X, 최일X

**Comment by JimJeon** [comment]
@yunitto 스터디 결정사항은 전부 Team으로 만들어서 스터디 repo 하나씩 주었습니다.

**Comment by minhoryang** [comment]
[Github 세미나를 Release Drive에 올렸습니다!](https://docs.google.com/presentation/d/1gwChpprEmwDFlA2IAGvhbdsReDAOy0wdMRmW4Wmb7RQ/present) ([.pdf](http://r.reluv.me/fVrB))
질문은 [제 AMA](https://github.com/minhoryang/minhoryang.github.io)에서 받습니다.

**Comment by taeguk** [comment]
모두 수고하셨어요~

**Comment by juice500ml** [comment]
@tmdghks0612 @yunitto @JimJeon 매 발표마다 사진이랑 문서 추합해서 드라이브 내에 있는 한 폴더에 다 정리해서 넣어주세요! 노파심에서 하는 말이지만 sogangrelease로 로그인되어있는 상태로요. 저 계정이 파일을 갖고 있어야 하는거니까요~

**Comment by JimJeon** [comment]
추합 - > 취합

**Comment by JimJeon** [comment]
네 알겠습니다!! 그런데 sogangrelease 드라이브에 올려달라는 말인가요?
뒷 부분이 잘 안 읽힙니다.. ㅠㅠ

**Comment by tmdghks0612** [comment]
그러게요 드라이브에서 계정이 파일을 갖고있다는 건..? 잘 모르겠네요. 어쨌든 곧 정리해서 올릴게요!

**Comment by juice500ml** [comment]
@JimJeon 넵 정확합니당 내 이름으로 2016 RELEASE에 업로드하게 되면 내 계정이 주인이 되게 됩니다!

**Comment by juice500ml** [comment]
@tmdghks0612 위에 있는 Github 세미나 .pdf도 다운받으셔서 드라이브에 정리해주세요! @minhoryang @yunitto 도 사진 찍으신 것 같은데 다 받아서 다같이 정리해서 올려주시구용~

**Comment by juice500ml** [comment]
드라이브에 Archiving이 끝나면 Issue를 닫도록 합시당

**Comment by minhoryang** [comment]
@juice500ml 소유권은 변경할 수 있습니다! 각자 자신의 소유권을 release에 귀속시키도록하죠.
제 사진을 업로드하고있습니다. 한 300MiB? (?!), 복사본을 보관하지 않을 예정이니, 부끄러우시면 삭제해주세요.
기록은 많이 남길수록 좋답니다.

![2016-03-27 3 47 20](https://cloud.githubusercontent.com/assets/1270855/14064177/48c0c270-f433-11e5-867b-6a8c763ec031.png)

**Comment by minhoryang** [comment]
전 사진 끝, 사진 가지고 계신 다른 분들이 이어서 해주세욧!

**Comment by tmdghks0612** [comment]
드라이브에 정리해뒀어요 이슈 클로즈합니다
