### ISSUE TITLE
릴리즈 페북 그룹을 만드는건 어떤가요?

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#37]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160323 Release Day [1]`
- **관련된 이슈들**:
  - 부모 이슈:   `null`
  - 자식 이슈:   `null`
- **추천하고 싶은 사람**:  페북 자주 가는 사람.
#### 설명:

만드는건 어떤가요?
할 꺼면 릴리즈 데이 전에 해결해서 그 때 다같이 가입하고 정리하는걸로 하죠
#### 확인:
- [ ] **@JimJeon**
- [ ] @Assignee

**Comment by yunitto** [comment]
저는 페이스북 그룹 있는것도 좋을것 같아요! 친목이나 행사홍보, 선배 컨택도 더 쉬워질거에요

**Comment by yunitto** [comment]
오늘 내로 결정하고 릴리즈데이 전에 만드는게 나을거예요

**Comment by juice500ml** [comment]
마감일 바꿨습니당~

**Comment by yunitto** [comment]
그런데 페이스북 페이지도 지금 관리가 안되고 있는데 굳이 그룹을 만들 필요가 있을까요?

**Comment by mandoriiiii** [comment]
페북 그룹 운영은 찬성입니다.
그런데 릴리즈 관련 그룹이 네이버 라인, 단체카톡방, 깃허브, 구글 공유드라이브 등등.. 물론 각자 장단점 및 특성이 다르지만 너무 많이 존재해서 정리도 필요할 것 같습니다.

**Comment by taeguk** [comment]
http://taeguk.me 처럼 release 관련 사이트들의 링크를 모아두는 게 어떨까요??

**Comment by yunitto** [comment]
@taeguk 어썸타이틀에 넣는거 어떤가요?

**Comment by mandoriiiii** [comment]
@yunitto 어썸타이틀에 넣기엔 당장 필요한 사안인 것 같아요.
일단 임시로 링크 모음을 만들어두고 차후에 엌섬타이틀에 추가하는 방식이 되어야 항 것 같습니다

**Comment by juice500ml** [comment]
페북 페이지가 생기면 네이버 밴드는 없어도 될 것 같은데요!

**Comment by mandoriiiii** [comment]
@juice500ml 깃허브 위키에 links 항목을 둬서 관련 사이트들을 정리해두는 건 어떨까요?
사이트별로 용도랑 특성을 적어두고 활성/비활성 사이트로 구분해둔다던지 아니면
필요없어진/사용 안 하는 사이트들은 아예 기재를 안 해두는 방법도 있구요 ㅋㅋ
어찌되었든 한 눈에 사이트들을 확인가능한 페이지는 있는게 좋을 것 같습니다
개인젇으로 릴리즈 웹페이지가 활용이 안되는게 안타깝기도 하구요 ㅠㅠ

**Comment by taeguk** [comment]
@yunitto @mandoriiiii  AwesomeTitle에 그냥 넣으면 될듯요. http://taeguk.me 는 단순히 html 파일 1개, css파일 1개, js파일 1개짜리 홈페이지에요. 그냥 가져가셔서 넣으면 될듯합니다.

**Comment by taeguk** [comment]
아니면 links.reluv.me 를 만드는건 어때요. 거기다가 link들을 등록...

**Comment by yunitto** [comment]
임시방편으로 여기 Readme에 링크를 정리해두고, 추후에 어썸 타이틀 메인화면에 정리해도 좋을것같아요! Readme는 아침에 제가 수정할게욧

**Comment by JimJeon** [comment]
링크 정리는 따로 이슈를 만들께요 페북 관련해서는 시크릿 그룹으로 만들면 밴드를 대체해서 사용하기 좋을거 같아요.
당장에 16들이 밴드로 초대도 안됏으니???까요???
(제가 밴드를 안써서 확인을 못햇어요)

**Comment by yunitto** [comment]
그러면 밴드도 없애고 페북 그룹도 생성하지않는걸로 결정하고 이슈 닫겠습니다.
