### ISSUE TITLE
릴리즈 지식인 프로젝트는 어때요?

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#38]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160326 Release Day [ 1 ]`
- **관련된 이슈들**:
  - 부모 이슈:   #36 
  - 자식 이슈:   `null`
- **추천하고 싶은 사람**:  
#### 설명:

AwesomeTitle 로그인 시스템이랑 연결하는건 어떤가용
15/16학번들 주축으로 flask/bootstrap로 만들어보는것도 좋아보여요! 나름 간단해보일 수도 있는듯.
릴리즈데이때 프로젝트 하고 싶은 사람들을 모아보죠!
@minhoryang 카톡 봇 언제 만들까용
#### 확인:
- [x] **@JimJeon**
- [ ] @Assignee

**Comment by minhoryang** [comment]
이슈를 네개로 나눠야해욧.
1. 로그인 : 이건 진짜 필요한데, 머리 속이 복잡하네요. 생각을 더 해봐야 할 듯 해용.
2. 세미나 : 이건 좋아요. 광희가 진행해줄래요?ㅋㅋㅋㅋㅋㅋㅋ #toss
3. 해커톤 : 릴리즈데이에 하는 것이 좋을까요?
4. 카톡봇 : 기술적으로 카톡봇이 어려워요. ;ㅅ; 예전에는 안쓰는 폰 한대만 있으면 됬는데, 지금은 그렇지 않다고 알고있어욧;ㅅ;
이렇게 .... ;ㅅ; @juice500ml

**Comment by juice500ml** [comment]
@minhoryang 카톡봇은 좀 더 알아볼께용 그리구 플라스크를 제가 할 수 있을까요..! ㅋㅋㅋㅋㅋㅋ 그것보다도 beautifulsoup 생각중이에요!

**Comment by taeguk** [comment]
카톡봇은 카카오톡회사에서 허락을 안해주기때문에 만들려면 카카오톡을 리버싱해서 프로토콜체계를 파악해야해요...(해킹을 해야하는 셈ㅠ) 그리고 만들어도 트래픽이 많아져서 걸리면 짤리구ㅠㅠ
대체제로서 텔레그램봇같은 경우는 telegram-cli와 lua를 통해 쉽게 만들 수 있어용!!

**Comment by JimJeon** [comment]
아예 멋진제목에 지식인 페이지를 만드는건 어떨까요?

**Comment by minhoryang** [comment]
@juice500ml GOTO [SGCSRelease/RFC](/SGCSRelease/RFC), AND FIND THE TEAMMATES
@taeguk GOTO [SGCSRelease/RFC](/SGCSRelease/RFC) TOO, AND UPLOAD YOUR PUSH IDEA
