### ISSUE TITLE
초보자용 이슈 작성을 만들어주세요

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#40]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160326`
- **관련된 이슈들**:
  - 부모 이슈:  `null`
  - 자식 이슈:  `null`
- **추천하고 싶은 사람**:  @JimJeon 
#### 설명:

이슈 작성법이 비임원진에게는 너무 어려워요! 비임원진은 제목/내용만 적을 수 있도록 템플릿 차원에서 짤막한 설명을 해주면 임원진이 와서 교통정리해주는 게 좋은 것 같아요. 
#### 확인:
- [ ] **@JimJeon**

**Comment by yunitto** [comment]
릴리즈데이에 설명할게요. 비임원진에게 그리 어렵지는 않다고 봅니다. 릴리즈데이에 조를 몇개 짜서 조별로 이슈 오픈해보면 다들 쉽게 사용법을 익힐 수 있을거에요

**Comment by juice500ml** [comment]
이슈 종류가 @yunitto  덕에 쉬워져서 필요 없어진 것 같습니다! 클로즈하겠습니다~
