### ISSUE TITLE
릴리즈 단체 티/후드를 찾고있어요!

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#41]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈: #15 (closed)
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @tmdghks0612 @yunitto @JimJeon 
#### 설명:

열심히 구글링으로 단체티 사이트를 알아보면서 디자인도 알아보고 있는중입니다.
수일 내에 카톡으로 디자인 투표를 받을게요.
#### 확인:
- [x] **@tmdghks0612**
- [ ] **@yunitto**
- [x] **@JimJeon**

**Comment by tmdghks0612** [comment]
디자인 투표는 활성회원방에서 바로 하는 건가요? 아니면 한 번 추려서 할 예정인가요?

**Comment by juice500ml** [comment]
한번 추려서 너댓개에서 고르면 좋겠네요~

**Comment by JimJeon** [comment]
릴리즈 데이 당일 날 "후드티 찾기 대회!!!" 처럼 하면 어떻겟냐는 이야기가 나왓습니다.
좋은거 같아서 일단 채택해서 ppt에 넣어놓았습니다.

**Comment by juice500ml** [comment]
#51 에서 처리하겠습니다.
