### ISSUE TITLE
Wiki 업뎃해주세요!

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#42]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160322`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @yunitto 
#### 설명:

라벨이 공지 없이 바뀐 것 같아요! 바뀐 라벨에 대해 위키 작성해주세요!
#### 확인:
- [x] **@JimJeon**
- [ ] @Assignee

**Comment by yunitto** [comment]
제가 할게요

**Comment by yunitto** [comment]
Issue Type와 Label의 차이점이 뭔가요? @juice500ml

**Comment by yunitto** [comment]
위키 업뎃 했습니다. 확인하고 문제없으면 이슈 닫아주세요 @juice500ml

**Comment by juice500ml** [comment]
@yunitto 수고하셨습니다!

**Comment by JimJeon** [comment]
@yunitto 수고하셨습니다.
