### ISSUE TITLE
XCODE 및 OS 업데이트가 생겼습니다!

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#43]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @charcoalbug 
#### 설명:

Xcode와 OS업데이트가 있으니 @charcoalbug 는 업데이트를 해주세요!
가능한 빨리 해야합니다! 캡스톤 디자인 수업에 차질이 생길 수도 있습니다. 내일까지 업데이트는 힘들 것 같으니 적어도 다음주 수요일 캡스톤 디자인 수업 전까지는 업데이트를 완료해주세요!
그리고 관리하시는 분들은 업데이트에 알림이 떠있으면 체크해주시고 관리시트에 적어주세요.
![2016-03-22 9 05 21](https://cloud.githubusercontent.com/assets/9067305/13951040/d0c17900-f071-11e5-84ed-cf2a948fa080.png)
업데이트 확인 대상은 xcode, OS업데이트가 주 입니다.
#### 확인:
- [x] **@charcoalbug**

**Comment by jmg7173** [comment]
업데이트 하는 시간까지 고려해서 내일 캡스톤 디자인 수업에 지장이 없었으면 좋겠습니다.

**Comment by jmg7173** [comment]
업그레이드 보니까 11시간쯤 걸리니 캡스톤디자인 수업 끝나고 업그레이드해주세요

**Comment by minhoryang** [comment]
https://support.apple.com/downloads/ 에서 정확히 그것만 빼갈 수 있어요!

**Comment by minhoryang** [comment]
그러니까 이번같은경우에는

**Comment by minhoryang** [comment]
[디지털 카메라 RAW 호환성 업데이트 6.18](https://support.apple.com/kb/DL1855?viewlocale=en_US&locale=en_US)
[iTunes 12.3.3](https://support.apple.com/kb/DL1814?viewlocale=en_US&locale=en_US)
OS X El Capitan 복구 업데이트 1.0 (안나오네요)
[OS X El Capitan 업데이트 10.11.4](https://support.apple.com/kb/DL1868?viewlocale=en_US&locale=en_US)
Xcode 7.3 (안나오네요)

**Comment by charcoalbug** [comment]
수업에 지장 없으면 안되니까 수업 이후에 업데이트 하겠습니다.

**Comment by yunitto** [comment]
@charcoalbug  다 업데이트 했나요? 완료하고 내일까지 이슈 클로즈해주세요.

**Comment by JimJeon** [comment]
xcode 업데이트 다 햇다고 하네요
os 업데이트는... 오늘 하겟습니다

**Comment by taeguk** [comment]
옛날에 릴리즈랩실컴터 전부 명령어 내리는 파이썬 스크립트 짜긴했었는데,,, @juice500ml

**Comment by juice500ml** [comment]
@taeguk 너가 짰던거 나한테 있더라ㅋㅋㅋ 너 지메일로 보내놨으니까 폴더 새로 만들어서 https://github.com/SGCSRelease/lab_management 에 푸쉬해주라

**Comment by JimJeon** [comment]
1번 5번 15번 컴퓨터는 사용중에 있어
이 셋을 제외하고 소프트웨어 업데이트 완료했습니다.

**Comment by mandoriiiii** [comment]
1번 5번 15번 업데이트 완료 후 이슈 닫아주세요~

**Comment by juice500ml** [comment]
@charcoalbug 다 됐나요?

**Comment by JimJeon** [comment]
완료했습니다.
