### ISSUE TITLE
신입/기존회원 친목 행사를 제안합니다

### ISSUE THREAD

**Issue by mandoriiiii** [SGCSRelease/ReleaseWorld#44]
- [ ] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160331`
- **관련된 이슈들**:
  - 부모 이슈:   멘토링 #19 릴리즈 데이#36 
  - 자식 이슈:   #50 
- **추천하고 싶은 사람**:  @chldlftjs  @tmdghks0612 
#### 설명:

( #19의 의견들을 먼저 읽고 와주세요 :) )
작년에 시도했던 멘토링의 경우 친목과 학업 두 마리 토끼를 잡자는 목표가 있었으나
여러 이유로 흐지부지 되었는데요 학업의 경우 이미 세미나와 스터디가 있으니 충분하다고 생각됩니다만 
친목 활동의 경우 좀 더 필요하다고 생각되어 제안해봅니다.
사족으로 마감일이 3월 31일인 이유는 친목을 위한 기획이기 때문에 가능한 한 빨리 진행되었으면 하는 바램 때문입니다.

친목도모 음료값 지원 행사입니다. 3가지 방식으로 진행되는데요
1. 기존 회원 간
   아직도 어색한 기존 회원끼리의 친목을 위해 같이 음료를 마시고 인증샷을 찍어주시면 
   음료값을 지원해드립니다! 
   단, 더 이상 친해질 필요가 없는 분들의 악용을 막기 위해 이 경우 
   '한 잔의 음료를 동시에 같이' 마시는 인증샷만을 인정합니다. 
   돈도 물론 한 잔의 음료값만 지원됩니다 
2. 신입/기존 및 신입/신입
   신입회원과 기존회원 분 혹은 신입회원 분 끼리 음료를 드시고 인증샷을 찍어주시면
   음료값을 지원해드립니다! 
   이 경우 인원수만큼의 음료를 드시고 그 만큼의 음료값을 지원받으시면 됩니다.
   다만, 신입+기존 조합의 경우 기존회원이 더 많을 경우 음료값은 (신입회원의 수 + 1)까지만
   지원됩니다.
3. 부끄러움이 많으신 신입분
   너무나 수줍으셔서 음료를 도저히 같이 못 마시겠다! 하시는 신입 분들을 위해 준비했습니다.
   기존이든 신입이든 타학회원의 도촬사진을 4장 이상 찍어오시면 혼자 드실 음료값을 지원해드립니다.
   도촬사진의 조건은 
   1) 사진 속에 대상이 명확히 인식 가능할 것
   2) 사진 속의 대상은 본인이 찍히는 줄 모를 것
   3) 사진 속 대상의 이름을 알 것 
   입니다. 
   이 경우도 악용을 막기 위해 도촬사진으로 드리는 음료값 지원은 1회만 지원됩니다..

친목 활동은 제안하고 싶은데 열심히 일하시는 임원진 분들에게 일거리를 늘려드리고 싶지는 않아서 가능한 한 구체적으로 기획해 봤습니다
다만 학회비 현황 같은 경우 상세히 알기가 어려워서 재정 상황이 안 받쳐줄 경우 시행하기 어려울지도 모르겠습니다 ㅠㅠ 
읽어보시고 가능할 경우에 진행해주시면 좋겠습니다 :) 
진행이든 안진행이든 확정날 경우 이슈 닫겠습니다 
#### 확인:
- [x] **@chldlftjs**
- [x] **@tmdghks0612**

**Comment by taeguk** [comment]
+1

**Comment by tmdghks0612** [comment]
3번은 진짜 생각도 못했네요 ㅋㅋㅋㅋㅋㅋ
신입회원이 8명인 걸 감안하면 재정이 크게 문제되진 않을 것 같...지만 확인 한 번 해볼게요.
별 문제 없으면 찬성+1입니당

**Comment by chldlftjs** [comment]
이대로 진행해도 충분히 좋아보이긴 하지만 친목의 양극화(?)와 같은 현상이 발생할 수 있을 것 같아요. 특정 대상이 정해져 있지 않으면 아무래도 조금이라도 기존에 친했던 사람들을 찾게 되니까요. 같이 관리하는 사람들끼리 커피타임을 가지게 만든다든지 아니면 게임에서의 퀘스트처럼 각 신입생마다 특정 인물에게 커피 얻어먹기 등의 미션을 준다든지 등의 약-간의 강제성이 있는 세부 이벤트로 다양한 사람들이 서로 친해질 수 있게 하는 것도 좋을 것 같아요.

**Comment by juice500ml** [comment]
ex) 이름에 티읕이 들어가는 사람은 오늘 커피타임 무제한! 이런 것도 좋을듯!

**Comment by mandoriiiii** [comment]
사실 그래서 아예 14 15들마다
14김도현이 영혼없이 자는 모습 찍어오기!
14정연준의 생수 얻어마시기!
15전진우에게 개구리머리띠 씌우기!
이런 미션을 만드는 것도 생각해봤는데 아이디어를 내기가 힘들더라구요..ㅋㅋㅋㅋ
그치만 좋은 아이디어만 있다면 얼마든지 바꿔서 진행해도 좋을 것 같습니다!

**Comment by JimJeon** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 아이디어 맘에 드는데요??
다같이 이거 함 구체화 시켜보는거도 좋을거 같아요

**Comment by JimJeon** [comment]
만도리... 3번 ㅋㅋㅋㅋㅋ 도촬범...ㅋ ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 아옼ㅋㅋㅋㅋㅋ
너무너무너무너무너무너무너무너무 좋습니다. ㅋㅋㅋㅋ

**Comment by JimJeon** [comment]
우선 도촬 프로젝트는 채택하기로 했습니다.

위에 제안한 미션 관련한 부분은 아직 논의가 되지 않았습니다.

**Comment by JimJeon** [comment]
미션 관련한 부분은 새로운 이슈 열어서 논의 해보도록 합시다.

**Comment by gomamon** [comment]
오오오오오오오!좋아요!

**Comment by mandoriiiii** [comment]
일단 도촬만 진행하는걸로 확정하고 이슈 닫습니다~~ #50에서 논의합시다
