### ISSUE TITLE
프로젝트 레이블을 만들어주세요!

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#45]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160326`
- **관련된 이슈들**:
  - 부모 이슈:   `null`
  - 자식 이슈:   `null`
- **추천하고 싶은 사람**:  @JimJeon @yunitto 
#### 설명:

세미나 레이블, 스터디 레이블은 있는데 프로젝트 레이블은 없어요.
나중에 사람들을 모은다던가 그럴때도 여길 이용하면 좋지 않을까요..? 의견 부탁드려요!
ex) #38 의 경우 프로젝트 레이블이 있으면 좋을 듯...
#### 확인:
- [x] **@JimJeon**

**Comment by JimJeon** [comment]
만들었어요~

**Comment by JimJeon** [comment]
만들었어요~
