### ISSUE TITLE
5/7 (토) 두번째 릴리즈 데이를 준비해야해요!

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/ReleaseWorld#46]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160430 #릴리즈데이2`
- **관련된 이슈들**:
  - 부모 이슈:   #36
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @SGCSRelease/16-spring 
#### 설명:

두번째 릴리즈 데이를 첫번재 릴리즈 데이를 하기 전에 올리는 이유는,
- 두번째 릴리즈 데이의 세미나 준비와
- 첫번째 릴리즈 데이에서 정해진 내용을 여기에 기록하기 위함입니다.
#### 확인:
- [x] **@JimJeon**
- [ ] @tmdghks0612

**Comment by minhoryang** [comment]
#20 에서 언급한, 이혜민 선배님의 구글PM세미나는, 아마 판교에서 이루어질 것 같구요. 10명 이내라면 자택에서 이루어질 것 같습니다. 그래서 제가 한 달 전에는 꼭 원하는 주제와 예상 인원을 연락드리고 싶습니다. 참고 바랍니다.

**Comment by JimJeon** [comment]
이 때 한 달 동안 진행된 스터디, 세미나 등 여러가지 행사에 대한 피드백을 했으면 좋겠습니다.
그리고 추후에 있을 해커톤이나 릴리즈 내부 대회(?) 행사를 준비하기 시작했으면 좋겠습니다.

뭐 팀코딩대회(아직 어떻게 할진 잘 모르겠지만) 뭐 이런 것들의 일정을 구체적으로 잡았으면 좋겠어요.

**Comment by minhoryang** [comment]
**세미나 주제를 받아요!**

**Comment by JimJeon** [comment]
@jmg7173 가 멋진제목 세미나를 해주었으면 해요!

**Comment by minhoryang** [comment]
![awesometitle](https://cloud.githubusercontent.com/assets/1270855/14278468/d8bb1a02-fb62-11e5-9c1c-441bc8bf0df3.png)

**Comment by JimJeon** [comment]
+1ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by jmg7173** [comment]
흐윽... 저런 메인화면이면 세미나 안할꺼예욧! 흥

**Comment by taeguk** [comment]
오 저거 좋다 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저거로gogo

**Comment by minhoryang** [comment]
고객님의 취향을 반영했습니다!
![2016-04-06 1 57 30](https://cloud.githubusercontent.com/assets/1270855/14306195/8eb9f53e-fbff-11e5-9e54-0e0e98b7083e.png)

**Comment by minhoryang** [comment]
제 취향을 반영했습니다.
![2016-04-06 1 59 46](https://cloud.githubusercontent.com/assets/1270855/14306216/da8384c6-fbff-11e5-988c-8f7deb264d73.png)

**Comment by minhoryang** [comment]
다음 타겟 받습니다.

**Comment by jmg7173** [comment]
ㅂㄷㅂㄷ...

**Comment by taeguk** [comment]
이 날 총엠이래요

**Comment by tmdghks0612** [comment]
오늘 날짜조정할까 얘기해보기로 했어요 --> 5월 7일 토요일로 변경했습니다!

**Comment by minhoryang** [comment]
저도 세미나를 하려구요. 될까요?
- **집 번호를 준다는 것은**
  - _세상의 많은 구현_
    - 편한 세미나일거에요 30분 예상하고있어요.
    - 간단한 실습 및 간단한 대회가 열릴 예정입니다.

**Comment by tmdghks0612** [comment]
오오 민호 센빠이의 세미나라면 기대가 되네요.
그런데 세미나 내용이 어떤 건지 조금만 더 알려주실 수 있나요?

**Comment by yunitto** [comment]
**세미나 순서**
1. 웹디자인 세미나(1시간+) @kokosake 
2. [집 번호를 준다는 것은(3~40분) @minhoryang ](https://docs.google.com/presentation/d/17Il37US8rjGB0EuWN2RB_VUg13IOF_n89VV6axmRiBU/present)
3. [어썸타이틀 개발기(30분) @jmg7173](https://goo.gl/KrzT4F)

팀 코딩 대회를 할까요 아니면 소풍을 갈까요? @SGCSRelease/team 의견달아주세요~

**Comment by jmg7173** [comment]
혹시 어썸타이틀 개발기 세미나에서 듣고 싶거나 궁금한 이야기가 있나요! @SGCSRelease/team

**Comment by mandoriiiii** [comment]
웹/파이썬 개밣환경 및 깃허브를 이용한 협업은 처음이셨던 걸로 아는데 처음에 적응해나갔던 과정이 궁급해요

**Comment by tmdghks0612** [comment]
팀 코딩 대회는 의견 나눠보고 준비를 해봤는데 좀 더 시간이 필요할 것 같아요

**Comment by minhoryang** [comment]
세미나 PPT 위에 순서부분에 링크 걸었습니다.
녹화 동영상은 변환 다 되면, 다운받아서 드라이브에 올릴게요.
