### ISSUE TITLE
릴리즈 회계장부를 만들어주세요

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#47]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160326`
- **관련된 이슈들**:
  - 부모 이슈: 
  - 자식 이슈: #48 
- **추천하고 싶은 사람**:  @tmdghks0612 
#### 설명:

드라이브로 관리하면 좋을 것 같아요!
#### 확인:
- [ ] **@JimJeon**
- [x] @Assignee

**Comment by tmdghks0612** [comment]
드라이브 만들었어요!
@JimJeon 짐전의 돈도 적는다!

**Comment by mandoriiiii** [comment]
작년에 쓰던 양식도 아마 @fuzzythecat 한테 있을껍니다 제가 동아리에서 빼돌려줬었는데
참고하세요 ㅋㅋ
