### ISSUE TITLE
예산안을 만들어요!

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#48]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `가능한한 빨리`
- **관련된 이슈들**:
  - 부모 이슈:   #47 
  - 자식 이슈:  
- **추천하고 싶은 사람**: @tmdghks0612 
#### 설명:

한 학기동안 있을 행사 및 여러가지 기타 등등의 일들에 예산을 책정하여 대략적인 지출을 계획해놓아야 합니다.
#### 확인:
- [x] **@JimJeon**
- [x] @tmdghks0612

**Comment by JimJeon** [comment]
예산안을 짜기 전에 먼저 이번 학기에 할 행사들을 확정지었으면 좋겠어요.
최소한 이정도는 이번 학기에 꼭 하겠다!!! 이런거 말이에요.
더 추가될 수는 있지만 여기 있는 것들은 빼지는 않겠다!! 이런식으로요
예를 들어서 해커톤은 언제 할건지, 만약에 그걸 방학 때 한다면 이번 학기 중에는 뭔가 다른 행사를 했으면 좋겠다는 바램이거든요,....

**Comment by tmdghks0612** [comment]
일단 드라이브로 공유하면서 써보죠

**Comment by chldlftjs** [comment]
작년 예산안도 구글 드라이브 아니었나요? 그대로 이어받으면 될 것 같은데요.

**Comment by JimJeon** [comment]
@chldlftjs 가계부가 아니라 예산안이요

**Comment by mandoriiiii** [comment]
이번학기에 남은 일이라면 
봄소풍-4,5,6월 릴리즈데이-종총-여름엠티 에다가 미션 임파서블 행사 정도가 
존재할 것 같아요. 6월 릴리즈 데이는 1학기 마지막이니 만큼 뒷풀이가 공식이 되는 것도 괜찮아 보입니다. 
추가로 기획중인 해커톤/버그톤/윤영이를 괴롭혀라 행사 등이 있나요?
@JimJeon  @tmdghks0612

**Comment by juice500ml** [comment]
@JimJeon @tmdghks0612 @chldlftjs 어떻게 되어가고있나요?

**Comment by tmdghks0612** [comment]
행사 할 것들이랑 비용 생각중인데 아직 완성이 안됐어요!

**Comment by JimJeon** [comment]
우선 예산안을 만들어서 드라이브에 올려놓았는데 저 혼자 만든거라서
다른 사람들의 의견이 반영이 안 되어 있어요.
각종 피드백 받겠습니다.

**Comment by yunitto** [comment]
@JimJeon 수고많았어요! 드라이브에 코멘트 달아놨는데 일단 한번 확인해주시고, 주중에 랩실에서 만나서 같이 수정해요 :)
