### ISSUE TITLE
릴리즈 위키 프로젝트도 하고싶어요

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#49]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `???`
- **관련된 이슈들**:
  - 부모 이슈:   ???
  - 자식 이슈:   ???
- **추천하고 싶은 사람**:  @JimJeon
#### 설명:

ReleaseWiki라고 해서 유머러스한거도 좋고 전문적인 내용도 좋고
그냥 진짜 위키피디아 처럼 생각나는대로 릴리즈 사람들이 수정하고 추가할 수 있는 위키 페이지를 만들고 싶어요.
#### 확인:
- [ ] **@JimJeon**

**Comment by chldlftjs** [comment]
신입생 중에 자기만의 위키피디아 페이지를 만드신 분이 있었다는데 그분의 도움을 받는 건 어떨까요?

**Comment by minhoryang** [comment]
위에 링크 달아놓았어요. 포털과 합치는걸 원하신다면, 이 이슈를 닫고 저기로 이동해 주시구요.
아니라면 저쪽에 의견을 전달해주시고 여기에도 알려주세요!
기다리겠습니다.

**Comment by minhoryang** [comment]
@juice500ml 광희가 위키를 만들기 위한 몇가지 기술들을 써 봤어요. flask-markdown + CodeMirror. 이 두개에 Git만 관리하면 위키아닌가욧? 머릿속에선 거의 선이 그려졌는데!

저도 도와드릴 수 있어요!

**Comment by minhoryang** [comment]
앗! @JimJeon 님. 제가 [SGCSRelease/RFC](/SGCSRelease/RFC) 라는 기획안 저장소를 만들었는데, 만약 #53 에 힘을 실어주시는 것이 아니라면, '위키를 만들자'는 이슈도 RFC로 옮겨주시면 어떤가요?

**Comment by JimJeon** [comment]
엇! #53 이쪽에 힘을 실어줄지는 잘 모르겟어요...
사실 저는 지금의 홈페이지가 어떻게 될지 모르겠거든요 @hubaimaster 와 @juice500ml 께서 수정을 하려고 기획을 했었다는 이야기를 했었던거 같은데... 수정이 된 후에 모바일 지원이라던가 지금보다 훨씬 가벼워진다던가 하지 않는이상 저는 차라리 @SGCSRelease/awesometitle 이쪽으로 보내고 싶은 심정이거든요. 

그래서 제 생각은 !!! 우선은 RFC로 옮기겠습니다. ㅎㅎㅎ

**Comment by minhoryang** [comment]
그럼 이슈를 클로즈하고, 둘의 이슈를 끊기로 하죠. RFC로 옮겨주시면 이슈로 지원사격 하겠습니다!
