### ISSUE TITLE
임원진_git

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#5]
- [x] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [x] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 #개총 준비`
- **관련된 이슈들**:
  - 부모 이슈:  NULL
  - 자식 이슈:  NULL
- **추천하고 싶은 사람**:  @JimJeon 
#### 설명:

현 임원진을 초대해야 합니다!
#### 확인:
- [x] **@JimJeon**

**Comment by juice500ml** [comment]
초대해야 하는 사람(Github 아이디가 없는 사람)
- [x] 최윤영
- [x] 최일선

**Comment by JimJeon** [comment]
초대했습니다.
가입되면 임원진들은 체크를 해주세요.
- [x] 최윤영
- [x] 최일선
- [x] 유혜수
