### ISSUE TITLE
미션 임파서블 for 릴리즈

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#50]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `???`
- **관련된 이슈들**:
  - 부모 이슈:   #44 
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @EVERYBODY
#### 설명:

![2016-03-25 9 38 20](https://cloud.githubusercontent.com/assets/16199830/14044288/03011b84-f2d2-11e5-8788-428d51dc9c85.png)

이런걸 제안 받았는데요....
여러가지 의견들을 받아서 미션지를 만들어서 수행하는 방식으로 해볼까 합니다..
이외에도 구체적인 의견들 받습니다.
#### 확인:
- [ ] **@JimJeon**

**Comment by minhoryang** [comment]
@SGCSRelease/team 소환

**Comment by tmdghks0612** [comment]
미션 수행은 기존회원들도 참가했으면 좋겠어요
특히 도촬!

**Comment by JimJeon** [comment]
도촬은 다른 행사잖아요.....
이건 도촬이랑 다른 행사예요....

**Comment by juice500ml** [comment]
다섯 명 이상 모아서 @charcoalbug 앞에서 붐붐붐붐붐붐촵촵 하기. @jmg7173

**Comment by JimJeon** [comment]
붐붐붐붐붐촵촵촵

**Comment by jmg7173** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 고통받는 @charcoalbug ...

**Comment by tmdghks0612** [comment]
붐붐붐붐붐붐촵촵

**Comment by JimJeon** [comment]
아무래도 이건 지금 당장 하기에는 무리가 있는듯 해요.
일단 닫겠습니다.
