### ISSUE TITLE
단체티 받아욧!!!!!

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#51]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `10mins from now`
- **관련된 이슈들**:
  - 부모 이슈:   #41 
  - 자식 이슈:  
- **추천하고 싶은 사람**:  

조건
1. 3만원 이내
2. 예쁜거 무조건 예쁜거
3.  너무 두껍지 않은 것(후드집업 정도의 따스함)
4. 릴리즈 로고를 넣을 수 있어야 해요

선정되신 분께 소정의 책임감을 드립니다!

각자 맘에 드는 단체티 페이지 링크를 댓글로 올려주세요!!!

**Comment by tmdghks0612** [comment]
![2016-03-26 2 26 59](https://cloud.githubusercontent.com/assets/9067305/14058276/aaf76942-f35e-11e5-8b94-e7c2cd50f46d.png)
http://www.tgoboja.com/product/detail.html?product_no=142&cate_no=61&display_group=1

**Comment by tmdghks0612** [comment]
![2016-03-26 2 28 08](https://cloud.githubusercontent.com/assets/9067305/14058289/e169eebe-f35e-11e5-9f60-169616891e29.png)
http://www.mrtee.co.kr/shop/shopdetail.html?branduid=1125053&xcode=018&mcode=002&scode=&type=Y&sort=order&cur_code=018&GfDT=Z2x3UQ%3D%3D

**Comment by chldlftjs** [comment]
![2016-03-26 2 29 26](https://cloud.githubusercontent.com/assets/9067305/14058295/03fd4b38-f35f-11e5-951b-752f8d656978.png)
http://www.kakaot.com/product/detail.html?product_no=1673&cate_no=24&display_group=1

**Comment by tmdghks0612** [comment]
![2016-03-26 2 30 09](https://cloud.githubusercontent.com/assets/9067305/14058300/1ff40f70-f35f-11e5-8c72-0f21bd0bfc57.png)
http://www.dream-t.co.kr/shop_goods/goods_view.htm?category=010A0000&goods_idx=82874&goods_bu_id=

**Comment by diana917** [comment]
![2016-03-26 2 31 16](https://cloud.githubusercontent.com/assets/9067305/14058306/446d56f4-f35f-11e5-8af1-d01146ad5dc0.png)
http://www.teamt.net/product/detail.html?product_no=1444&cate_no=27&display_group=1

**Comment by JimJeon** [comment]
http://www.teeclub.co.kr/shop/goods/goods_view.php?goodsno=3787&category=021

귀가 달렸어요!!!!!! 꺗!
가격은 22,000원!

![2016-03-26 2 29 09](https://cloud.githubusercontent.com/assets/16199830/14058302/2598fb16-f35f-11e5-9cf5-36204dc68856.png)
![2016-03-26 2 29 17](https://cloud.githubusercontent.com/assets/16199830/14058303/269d4b8e-f35f-11e5-92ff-9f4eff95d244.png)

**Comment by sjlee2016** [comment]
![2016-03-26 2 30 10](https://cloud.githubusercontent.com/assets/17876276/14058309/6032916a-f35f-11e5-8652-c0304e21b6a1.png)
http://www.brotherco.co.kr/product/detail.html?product_no=283&cate_no=33&display_group=1

**Comment by JimJeon** [comment]
j민교... ㅂㄷㅂㄷ

**Comment by JimJeon** [comment]
여러분 이성적으로 생각해요
윤영이랑 남규가 귀 달린 거 입으면 얼마나 귀엽겠어요!!!!!!

**Comment by JimJeon** [comment]
왜.... 왜,...... 싫어하는 거예요......

**Comment by juice500ml** [comment]
상위 다섯개를 추려서 릴리즈 활성원 톡방에서 정하는거로 합시당~

**Comment by minhoryang** [comment]
여러분 이성은 귀에 달려있지 않아요!

**Comment by mandoriiiii** [comment]
여러분 지금 의견표시가 너무 다양한데 다들 손가락 위 아래 따봉 중에 하나만으로 의사표시를 하셔서 위 따봉 빼기 아래 따봉 수로 상위 5개를 추리는 게 어떨까요~ 전체회원 소환 어케하지 흑흑

**Comment by juice500ml** [comment]
@SGCSRelease/team
