### ISSUE TITLE
새 로고를 만들어 봐요

### ISSUE THREAD

**Issue by raon0211** [SGCSRelease/ReleaseWorld#52]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  X
- **관련된 이슈들**:
  - 부모 이슈:   #(이슈 번호)
  - 자식 이슈:   #(이슈 번호), ...
- **추천하고 싶은 사람**:  
#### 설명:

이제 단체 티를 만들고 하잖아요,
단체 티에 이제 릴리즈 로고가 들어가야 할텐데
다들 어떻게 생각하시나 모르겠는데 사실 지금 로고가 최신 트렌드에는 좀 안 맞는 부분이 있잖아요..

그래서 로고를 제가 한 번 새로 만들어 볼까 하는데
다들 새 로고의 필요성에 관해 어떻게 생각하시나 궁금해요

<img src="http://wiki.akarus.com/media/raw/%EC%95%84%EC%B9%B4%EC%9C%84%ED%82%A4.png" width="300">

위에는 제가 지난 2월에 만들어 본 로고입니다
좀 비슷한 배치로 아이콘을 예쁘게 만들어서
아이콘을 후드에 박는 식으로.. 하면 어떨까 생각해요

**Comment by yunitto** [comment]
음 저는 현재 릴리즈 로고도 좋아요!! 새 로고의 필요성은, 새로 만든 로고가 예쁘고 릴리즈를 잘 대표한다면 자연스레 생기지 않을까 싶네요. 한번 만드시고 공유해주세요!! 기대할게요 :)

**Comment by juice500ml** [comment]
로고를 함부로 바꾸는게 나을지... 저는 의문이네요. 이번 해에 처음 시작한거라면 몰라도 이제 3년차가 된 학회이고, 선배님들이 남긴 흔적/유산이라는 생각이 들어서요!

**Comment by raon0211** [comment]
<img src="http://learn.suhj.in/Release.png" width="402">

아침동안 만들어 봤어요

일단 왼쪽 상단의 세모는 소문자 'r'을 따서 깃발 모양으로 만들어 봤구요
글꼴은 좀 진취적으로 보이려고 삐침 없는 글꼴에 e를 10도 정도 기울였네요..

좀 무난한 느낌이긴 한데 어떨까 모르겠어요

**Comment by juice500ml** [comment]
릴리즈에 펭귄이 들어가게 된데는 이유가 있는데요, 저희 이전에 릴랩을 관리하던 인원이 SLUG 라는 분들인데, 그 당시에는 썬 마이크로시스템즈 사에서 나온 리눅스 컴퓨터를 사용했기 때문에 썬랩이라 불렸고, Sogang Linux User Group 이라는 이름을 갖고 있었어요. 저희는 그걸 이어받게되어서 펭귄이 로고에 들어가게 되었어요. 로고가 이쁜 것(!)과는 별개로 이유가 있어야 한다고 생각해서... 제가 좀있다가 고등학교때 동아리 뱃지를 만들 때 기획했던 걸 올려드릴테니 참고해주세용!

**Comment by juice500ml** [comment]
[incores_logo.zip](https://github.com/SGCSRelease/ReleaseWorld/files/190759/incores_logo.zip)
흑흑 원본을 못찾겠어요 
![logo_h78](https://cloud.githubusercontent.com/assets/9067305/14063870/6a906664-f422-11e5-98bf-202e8d91877a.png) 여깃지롱! -jmg7173

**Comment by JimJeon** [comment]
펭귄은 우리의 상징이자 영혼!
아아 펭귄 펭귕! 페엥귀잉! 나무나도 아름답구나!

**Comment by raon0211** [comment]
저도 역사를 이어나가야 한다는 데에는 격하게 동의해요. 그런 역사가 있었다는 사실은 잘 몰랐네요..
다만 로고에 펭귄을 넣는 것이 역사를 이어나가는 것인지는 좀 더 생각해 볼 문제라고 생각해요

로고에 펭귄이 있다고 아, Release는 SLUG의 후신이구나. 라고 딱 떠오르지는 않잖아요?
당장 저만 해도 말씀 주시기 전에 잘 몰랐어요.. 좀 더 알아봤어야 했네요ㅠㅜ

제 의견은, 릴리즈가 지금은 더 이상 리눅스 학회가 아닌 일반 종합적인 학회잖아요.
학회 랩실만 해도 지금 모두 아이맥을 쓰고 있고..
그래서 모두와 함께 좀 더 융통성 있게 로고를 생각해봤으면 좋겠어요..^^ 제 의견이니 그냥 참고만ㅎㅎ

**Comment by juice500ml** [comment]
@raon0211 제 말은 (저 로고를 만드신) 선배님들이 아직 Release 전체톡방에 있으니 그분들도 납득 가능한 설명이 있었으면 했어요 헤헤

**Comment by raon0211** [comment]
아.. 잘못 이해했어요 물론 만약, 바꾼다면 모두의 동의를 받고 바꿔야겠죠
큰 문제인만큼, 언제 한 번 단톡방에서나, 아니면 다음 릴리즈 데이 때 의논이 필요하다고 생각해요

로고에 대한 설명은, 전 컨셉을 앞으로 나가는 진취성으로 잡았는데
일단 깃발을 모티브로 했고.. 파란색도 그런 의미에서 사용했어요
한 편으로는 'r'을 형상화하기도 했구요

폰트의 경우에도 존재하던 폰트에 꽤 변형을 가해서
r의 모양도 바꾸고, e도 기울이고 했거든요.. 좀 새롭고 참신해 보이게
그런 의미에서 보자면 꽤 젊어 보이는 로고가 아닐까.. 생각해요

**Comment by minhoryang** [comment]
+1 좋은 제안입니다.

기존의 저 로고를 만들 때 옆에서 홀리블랙워터(콜라) 마시고 있었던 지나가는 행인1입니다.
(R914 관리실에 쳐들어가서 작업을 했었죠.)

요즘 예쁜 폰트가 많이 나오긴 했죠. 로고 만들기에 지금처럼 좋은 분위기가 없는 듯 해요.

그리고 사실 과거 SLUG라는 동아리가 있었다는 사실을 우리가 page한 부분을 할애해서, 또는 릴리즈 개총에 인트로로 설명을 한 적도 없기에, 당연히 모르시는 것도 이해가 됩니다. 이건 이 기억을 공유하고 있는 선배들이 책임지고 남겨야 할 기록물 중에 하나이지요. 우선순위도 높구요.

지금의 로고가 무슨 뜻을 가지는지는 사실 저도 모르겠습니다. 뭔가 지금같이 정신없는 분위기에 일조한 것 만은 확실한 것 같아요. 그리고 저는 이 분위기를 매우 매력적으로 느낍니다. 릴리즈 뿐만 아니라, 잠깐 취해 들어온 릴리즈의 친구들도 많은 만큼요.

그런 의미에서 아마 다음 로고를 제가 만든다고 한다면, 좀 더 정신없는, ... 예를들어 로고 사이에 캠프파이어가있고,... 마법사모자(?!)까지는아니지만 뭔가 마녀사냥(?!)하는... 뭐 무슨느낌인지 아실거라 생각합니다. (실현가능성은 물론 0%입니다.)

CI와 BI를 디자인 하는 것은, 공동체를 이해하는 일이 선행되어야 합니다.
조금 더 릴리즈를 즐겨주시고, 물고 뜯고 핥고 한 다음에
구성원들의 설득이 굳이 필요없는 과정이 매우 아름답지 않을까요?

무난한 CI는 아무도 원치 않고, 잊혀질 겁니다.
슬프지만요.

릴리즈 소 프로젝트의 BI로는 손색없어 보입니다.

**Comment by raon0211** [comment]
그렇군요 ㅋㅋ 릴리즈에 대한 이해가 선행되었어야 했는데 좀 서두른 느낌이 있습니다.
후드를 맞춘다길래, 좀 더 좋은 디자인의 로고가 들어갔으면 했던 마음이 사람을 급하게 만들었나 봅니다.
좀 더 릴리즈에 대해 알아간 후 다시 한 번 요청해 보겠습니다. 감사합니다.

**Comment by minhoryang** [comment]
@raon0211 제 마음을 이해해 주셔서 고맙고 감사합니다.
