### ISSUE TITLE
(가칭) Release 포털 개발에 관련된 건

### ISSUE THREAD

**Issue by raon0211** [SGCSRelease/ReleaseWorld#53]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  X
- **관련된 이슈들**:
  - 부모 이슈: #49
  - 자식 이슈: 
- **추천하고 싶은 사람**: 
#### 설명:

읽기 싫어하시는 분들을 위한 3줄 요약
1. Release에 필요한 기능이 많음(공개되지 않은 이슈 트래킹 시스템, 위키, 공지사항 등)
2. 개발에 대한 다들 의견이 어떠한지?
3. 웹디자인은 할 수 있는데 백엔드 쪽(실제 프로그래밍) 경험이 있으신 분이 필요

release.sogang.ac.kr을 보고 왔는데 좀 더 기능이 추가됐으면 좋은 부분이 많았어요

무엇보다 여기 GitHub는 모든 사람들에게 열린 공간이다 보니까
여기에 쓰는 모든 정보가 Google 검색 결과에 노출되는 등의 부작용이 있어요
그러다보니까 민감한 정보는 올리기가 어렵구요..

그래서 **NodeBB**와 같은 포럼형 웹 프레임워크를 도입해서 정보의 선택적 제공이 필요하지 않을까.. 생각해요
(NodeBB를 활용하면 이렇게 나와요: https://community.nodebb.org/)
#49 번 이슈를 보면 볼 수 있듯 Release 위키 만들었으면 하는 분들도 계시고 하니까

복합적으로 필요한 모든 기능들, 그러니까 이슈 트래킹/위키/공지사항 등의 기능을 담은
(가칭) Release 포털을 만들었으면 좋겠어요

웹디자인 쪽은 제가 확실히 맡을 수 있는데,
(지난 웹디자인: wiki.akarus.com, regi.kr 등)
기능 구현은 그렇게 익숙하지가 않아서 도움이 좀 필요한 부분이 있는데
혹시 웹 개발 쪽 경험이 있으신 분이 있을까요?

의견 부탁드려요..^^

**Comment by minhoryang** [comment]
@SGCSRelease/awesometitle 이쪽 사람들이 백엔드 잘해요!

**Comment by juice500ml** [comment]
업무처리를 깃헙 이슈로 관리하게 된건 어느정도 깃헙에 친숙해졌으면 좋겠다-라는 철학을 담고 있었어요! 그리고 홈페이지에서 관리하기보단 깃헙에서 관리하는게 깃헙을 자주 쓰는 사람 입장에선 접근성이 훨씬 좋으니까 그런 것도 있었구요. 이미 만들어진 프레임워크 안에서 돌리니까 관리도 편하고 안정적인 것도 있구요. 어쨌든 이런저런 이유로 그렇게 되었어요! 이번 학기 처음 시작해보는거라 좀 더 실제로 돌려보면서 하는게 좋을 것 같아요.

**Comment by juice500ml** [comment]
릴리즈 홈페이지 리뉴얼의 경우는 @hubaimaster 과 함께 이야기해보시는건 어떨까요? 이미 기획도 좀 나왔었고, 어느 정도 진전되었다고 알고 있습니다.

**Comment by raon0211** [comment]
개인적으로 카톡 드리면 될까요?

**Comment by minhoryang** [comment]
여기에서 이야기 해주시면 되요! @hubaimaster 소환!

**Comment by minhoryang** [comment]
1. 안녕하세요. 현재 SGCS Release에서는 Github Issues를 일의 진행 및 소통창구로 쓰고 있습니다.
2. release.sogang.ac.kr 은 과거 릴리즈 웹페이지 만들기 프로젝트의 일환으로 wordpress와 php로 만들어진 결과물이죠. 유지보수가 잘 안됬습니다. 원인으로는 개발보다는 유지보수의 느낌이 강해 구성원들에게 즐거움을 주기 어려웠다는 점, 그리고 대물림이 되지 않았다는 것이지요. 그런 의미에서 유지보수도 필요없고 진입장벽도 (나름)낮은, Github를 선택하여, 첫 세미나도 진행한 것이지요. 이슈는 공개될 수록 좋다고 생각합니다. 개인정보는 Google Drive에 저장하구요.
3. 지금 서버관리팀을 또 꾸리고 있습니다. 그러면 새 서버로 사용자들을 옮기고, 서비스들도 옮겨야겠지요. 제 개인적인 생각으로는 release.sogang.ac.kr 의 wordpress를 PPT등의 형태로 박제하고, 새 서비스로 옮겨가는 것을 생각해보려고 합니다. (아직 협의되진 않았습니다.)
4. 그러니 Github Issues나 release.sogang.ac.kr을 신경쓰지 마시고, 자유롭게 기획 해 주시면 되겠습니다.

어느정도 골격이 잡히면 [SGCSRelease/RFC](/SGCSRelease/RFC)로 기획안을 남겨주시면, 후대에도 도움이 되고, 팀원을 구하기에도 좋을 것 입니다.

FYI, 백엔드는 자신있어요.

**Comment by minhoryang** [comment]
프로젝트의 예상 타임라인을 적어주시는 것도 (언제부터 개발을 시작해서 언제 완료하고 싶은지), 팀원을 구하는데 많은 도움이 될 것 같습니다! 중간+벚꽃 어택이 생각보다 강하거든요 ㅠㅠ

**Comment by raon0211** [comment]
사실 좀 큰 프로젝트다 보니까 기말고사까지도 내다보는 프로젝트가 될 수도 있어요.
뭐 경우에 따라서는 디자인만 좀 빡세게 하면 금방 끝날 것 같기도 하지만요..

일단 구현해야 하는 기능을 정리해 보면,
- 포럼 형식 이슈 트래커
- 위키
- 공지사항, 프로젝트 정보 등을 알려주는 게시판
  이 될 거라고 생각해요.

개발 방법은 일단 두 가지로 생각하고 있는데요,

#### 첫 번째 방법

일단 빨리 끝낼 수 있는 방법은 완성된 프레임워크를 이것저것 짜맞춰서 만드는 방법이겠죠.
이 방법은 디자이너만 고생하면 금방 결과물을 낼 수 있다는 장점이 있습니다.
또 유지보수의 경우에도 간단합니다. 다만 커스터마이즈가 좀 힘들다는 단점이 있지만요..

사용할 수 있는 프레임워크는
- 포럼 형식 이슈 트래커: NodeBB(사용해본 적이 있는데 대단히 좋았습니다)
- 위키: MediaWiki(위키피디아가 쓰는 것), KotoEngine(저와 친구가 개발했습니다)
- 공지사항, 프로젝트 정보 등을 알려주는 게시판: 이건 금방 기능 개발할 수 있고, 아마 프레임워크도 많을 거예요.

이 경우 개발 기간은 약 2주 정도로 짧게 생각하고 있으나,
디자인 상황이나 중간고사(...)로 인해 4주~6주 정도 걸릴 수도 있어요.
저 혼자서도 충분히 가능합니다.

#### 두 번째 방법

개발자들의 의욕을 고취시키기 위해, 모든 걸 자체 개발하는 방법입니다.
일단 대단히 오랜 시간이 걸릴 겁니다.
GitHub와 같은 이슈 트래킹형 포럼과 위키 만들 생각을 하면 눈앞이 캄캄..

특히 고3 때 위키를 직접 Node.js로 친구와 만든 적이 있었는데 대단히 어려웠습니다.
아니, 어렵다기 보다는 할 일이 너무 많아서 귀찮았습니다.
그래도 다 만들고 나니 보람은 있었어요(...)

일단 포럼 형식 이슈 트래커는 처음부터 만들어야 할 것 같습니다.
위키는, 제가 C#으로 마크다운 파서를 한 70% 만들어 놓았다가 지금 잠깐 손을 놓았는데
따라서 파서 개발은 제가 하고, 나머지 뭐 로그인이나 수정 이런 HTTP 요청과 관련된 일들을 다른 회원분들이 해 주시면 될 것 같아요
(단, C#으로 만들어졌기에 ASP.NET MVC 사용이 필수적인 것으로 보여요)

이 경우, 개발 기간은 아마 한 학기는 걸리지 않을까 싶어요..
위키 만드는 데 하루에 1~2시간씩 해서 3~4개월 걸렸어요.

#### 제 생각

일단 제 생각은, 기존에 있는 완성된 프레임워크를 사용하다가(1안) 천천히 자체 개발 엔진쪽으로 이전해 가는 쪽이 나을 것 같아요.
이 경우가 시간도 절약되고 개발 의욕이 있으신 분이라면(..) 개발 의욕도 고취시키는 좋은 방법이 될 것 같네요 ㅋㅋ

그래서 오늘부터 시간 날 때 릴리즈 새 포털 웹디자인을 시작해볼까 하는데 어떤가요?

**Comment by minhoryang** [comment]
저도 C# .NET MVC4로 RestAPI 서버를 만들어 운영하고 있는 것이 있지요. 바로 R관 9층 엘레베이터에서 바로 나오면 보이는 TV Signage인데요. ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**우리가 모든 걸 다 만들 필요가 없다고 느낍니다.**
1. 예를 들어서 Markdown 파서는 이미 만들어진 것을 써본 적이 있어요.
- [임포트](https://github.com/juice-ryang/online-judge/blob/master/OnlineJudgeServer/__init__.py#L18)
- [선언](https://github.com/juice-ryang/online-judge/blob/master/OnlineJudgeServer/__init__.py#L59)
- [사용](https://github.com/juice-ryang/online-judge/blob/master/OnlineJudgeServer/templates/problem.html#L9)
- [실사용](http://judge.juice500.ml/week03/p1/)
- [실사용에 사용된 .md](http://r.reluv.me/fX7V)

1. 공동체의 기술 스택도 중요합니다. 같이 일할 팀원을 구해야하잖아요? 현재 @SGCSRelease/AwesomeTitle 의 개발진들은 위에서 보는 것 처럼 python3/flask microframework를 기반으로 높은 생산성(ㅋ)을 낼 수 있는 상태입니다. 참고해 주시면 좋겠습니다. 

@raon0211 어떻게 생각하시나요? 이 글을 읽고 목표치를 조금 수정해 주실 수 있으신가요?

**Comment by raon0211** [comment]
처음에 위키를 만들 때, 마크다운 파서를 그냥 가져와서 썼던 적이 있어요.
이 경우에는 근데 치명적인 문제점이 있어서, 결국 직접 만들어서 쓰지 않으면 안 됐다는 눈물의 이야기가..
문제점이 여러 개 있었는데 당장 생각나는 대표적인 예는
문법의 확장이 불가능했다는 슬픈 이야기

그러니까, [[내부 링크]]와 같은 문법을 전혀 쓸 수 없다는 이야기가 돼요

이런 부분을 구현하려면 위키 프레임워크와 파서가 서로 상호작용해야 하는데
(문서가 존재하는가? 등의 정보를 얻기 위해서)
그게 기존의 파서를 이용하면 어렵거든요..

그래서 결국 마크다운 파서는 직접 개발해야 해요..ㅠㅜ

**Comment by raon0211** [comment]
저 정말 협업 좋아합니다. 물론 프론트 엔드-백 엔드 끼리의 협업밖에 해 본적이 없지만요..
그래도 협업해서 2~3개 정도의 프로젝트는 성공시켰어요.

그런 의미에서 함께 이야기를 나누는 것 대환영입니다.
연락 창구를 제시해 주시면 바로 이야기를 나누고 싶어요.

**Comment by minhoryang** [comment]
`[[내부 링크]]`의 문법을 안 사용하는 것도 하나의 방법 아닐까요?

**Comment by minhoryang** [comment]
제 번호는 응-6247-359ㅇ입니다. 다음주 중으로 커피나 한잔하시죠!

**Comment by raon0211** [comment]
그러면 [내부 링크](http://wiki.release.sogang.ac.kr/w/내부 링크)와 같은 식으로 문서를 작성해야 해서, 참 어려운 부분이 있어요
번호 확인 했습니다^^ 지우셔도 돼요

**Comment by minhoryang** [comment]
공공재인데요뭘 ㅠㅠ

**Comment by minhoryang** [comment]
@저희가 백엔드를 만드니,
```markdown
[내부 링크](http://wiki.release.sogang.ac.kr/w/내부 링크)
```
가 아니라
```markdown
[내부 링크](내부 링크)
```
도 `/w/내부 링크`로 보낼 수 있구요.

그 외 여러가지 것들이 백엔드에서 가능합니다.

예를들면, `[[있는 문서]]`를 매번 프론트에서 작성해주는 것보다는, 백엔드 쪽에서 단어들을 다 DB에서 뒤져서 있으면 링크로 바꿔주는 것도 가능하구요.

**생각해보니 `[[있는 문서]]`를 프론트에 제공하기 전에, 백엔드에서 db를 검색하고, string replace를 해서, 프론트에 제공해줄 수 있습니다.**

고로 우리는 문법을 확장할 수 있네요.

**Comment by raon0211** [comment]
위키를 개발한 게 벌써 몇 개월 전이다 보니까 정확하게 문제점이 기억이 안 나는데요.
저희가 파서를 총 세 번 개발했는데 
일단 말씀해주신 것처럼 string replace를 통해 파서를 개발했던 적이 있었습니다. (첫번째)

대표적인 문제점이 제가 기억하기에 일단

1. 추가해야 할 문법이 많습니다. 내부 링크, 표(markdown에는 정말 간단한 표밖에 지원하지 않거든요), Definition List 등 위키에서 자주 쓰지만 마크다운에는 없는 문법이 많아요.
2. 코드가 좀 보기 어려워집니다. 파서 처리를 두 번이나 해야 해서 코드가 파서 하나를 쓰는 것보단 좀..
3. 결정적인 부분 1. **기존 마크다운 파서가 문법 확장을 지원하는지를 알 수가 없어요. 그리고 설령 알 수 있다 해도 마크다운 파서에서 DB에 접근을 할 수가 없어요.**<br>
일단 `[있는 문서](있는 문서)`라고 쓴다고 한다면 처리를 전에 하지 않는 이상 마크다운 파서의 문법에 걸립니다. 그리고 처리되면 어떻게 할 수 있는 방도가 없었어요 ㅠㅜ<br>
전에 처리를 하면 [내용](링크)에서 링크가 일일이 URL 형식인지 정규표현식으로 체크해야 하는데 매우 비효율적입니다. 또 전처리가 안 되는 경우에는 마크다운 파서 측에서 또 체크를 하니까 낭비가 커요.
4. 결정적인 부분 2. 느려요... 캐시로 극복이 되지만 그래도 성능 문제가 있어요. 몇백 밀리세컨드 단위긴 하지만요 ㅋㅋ
5. 저희가 Node.js를 이용해서 개발했었는데 Promise를 지원하는 파서가 없었습니다.

무엇보다 이미 C#으로 거의 제가 마크다운 파서를 다 만들어 뒀거든요..
자체개발 파서를 만들었는데 다른 파서를 이용할 필요가 있을까요?
TDD 방식으로 개발해 둬서 안정성은 있다고 생각해요

**Comment by raon0211** [comment]
아 생각해보니까 Python으로 개발하시는구나.. 헉
제가 진짜 혼신의 힘을 다해 포팅하면 안될까요...

그리고 파이선 코드 쓰셔도 괜찮아요 ㅋㅋ 어차피 코드 다 비슷비슷한데요 뭐

**Comment by minhoryang** [comment]
**Q.**
```
추가해야 할 문법이 많습니다. 내부 링크, 표(markdown에는 정말 간단한 표밖에 지원하지 않거든요), Definition List 등 위키에서 자주 쓰지만 마크다운에는 없는 문법이 많아요.
```

A. 저희가 그 문법이 필요하다는 보장이 없습니다. Markdown을 배우는 것도 어떤이에게는 고통일 수 있다고 생각합니다.

-----

**Q.**
```
코드가 좀 보기 어려워집니다. 파서 처리를 두 번이나 해야 해서 코드가 파서 하나를 쓰는 것보단 좀..
```
```
코드가 많이 비효율적으로 변합니다.
일단 [있는 문서](있는 문서)라고 쓴다고 한다면 처리를 전에 하지 않는 이상 마크다운 파서의 문법에 걸립니다. 그리고 처리되면 어떻게 할 수 있는 방도가 없어요 ㅠㅜ
전에 처리를 하면 [내용](링크)에서 링크가 일일이 URL 형식인지 정규표현식으로 체크해야 하는데 매우 비효율적입니다. 또 전처리가 안 되는 경우에는 마크다운 파서 측에서 또 체크를 하니까 낭비가 커요.
```

A. 최적화는 개발 이후 하는 것입니다. `[있는 문서](있는 문서)`는 당연히 마크다운이 담당해주고, 단지 우리가 해줄 것은 `[[있는 문서]]`만 `[있는 문서](있는 문서)`로 바꿔주는 것 뿐입니다. 문제의 정의를 어떻게 내리는가가 효율보다 더 우선입니다. 확장 가능한 Markdown Parser를 쓰는것도 하나의 선택입니다. 방금 flask-markdown의 코드를 훑어본 결과, 충분히 확장성이 있습니다. (re<->tmpl)

-----

**Q.**
```
느려요... 캐시로 극복이 되지만 그래도 성능 문제가 있어요. 몇백 밀리세컨드 단위긴 하지만요 ㅋㅋ
```

A. 속도도 최적화의 영역이고, 개발 이후에 할 수 있습니다. 그리고 Cache라는 좋은 솔루션이 있다는걸 알고 계시잖아요? flask-cache를 이용하면 이도 한줄로 해결 가능합니다. (어서오세요)

-----

**Q.**
```
저희가 Node.js를 이용해서 개발했었는데 Promise를 지원하는 파서가 없었습니다.
```

A. 오!!!! Promise!!!! Async와 Rx를 아는 후배를 만나서 너무나 기분이 좋습니다.
하지만 Promise가 없던 시기에도 Promise와 같은 '일을 미래로 던지고, 결과의 조합도 미래로 던지는' 컨셉은 구현 가능했습니다. (생산성의 문제였지요.) Rx로 짤 수 있는 문제라고 해서, Rx로 풀 필요는 없습니다.
특히나 우리에게는 Cash나 Cache가 있습니다.

-----

**Q.**
```
무엇보다 이미 C#으로 거의 제가 마크다운 파서를 다 만들어 뒀거든요..
자체개발 파서를 만들었는데 다른 파서를 이용할 필요가 있을까요?
TDD 방식으로 개발해 둬서 안정성은 있다고 생각해요
```

A. 후배들이 배워야 할 코드와 지식의 양이 기하급수적으로 증가합니다.

**Comment by raon0211** [comment]
그렇게까지 혼신을 다해 말씀하신다면 ㅋㅋㅋ 알겠습니다 그러면 다음에 같이 차 마시면서 이야기해봐요

**Comment by minhoryang** [comment]
넵! 기대하겠습니다!

**Comment by raon0211** [comment]
아 맞아 웹디자인 쪽은 어떻게 할까요?
저 웹디자인 경력이 꽤 돼서 혹시 HTML/CSS 배우고 싶으시거나 알고 계신 분 있으시면 같이 진행하고 싶어요

**Comment by minhoryang** [comment]
웹디자인 스터디를 만들기엔 좀 늦었나요?
옆에서 배우고싶습니다

**Comment by raon0211** [comment]
헛 ㅋㅋㅋ 하면 좋죠 ㅠㅜ 간단히 진행하는 정도라면.. 자세한 건 민감하니 카톡으로 연락드릴게요

**Comment by minhoryang** [comment]
?! 전혀 민감하지 않는데요 ;ㅅ;ㅠㅠㅠㅠ

**Comment by raon0211** [comment]
제가 민감해서요ㅋㅋㅠㅠ 닫힌 곳에서 가급적이면 말하는 걸 좋아해요

**Comment by minhoryang** [comment]
다음주 만날 때 이야기하도록하죠.
