### ISSUE TITLE
원활한 git사용을 위해 http://pcottle.github.io/learnGitBranching/에 도전하세요!

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#54]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  git을 사용하고싶은 모든 학회원분들!
#### 설명:

http://pcottle.github.io/learnGitBranching/ 를 정복해봅시다!
![2016-03-26 6 43 37](https://cloud.githubusercontent.com/assets/9067305/14059403/3e16b326-f383-11e5-937a-4e367f04625e.png)
![2016-03-26 6 44 07](https://cloud.githubusercontent.com/assets/9067305/14059404/415fb780-f383-11e5-8398-5a1118536e7d.png)
![2016-03-26 6 44 16](https://cloud.githubusercontent.com/assets/9067305/14059405/42970cf2-f383-11e5-8468-40446743d753.png)

**Comment by minhoryang** [comment]
저도 다 했어요! 그런데 제발 rebase는 실제 환경에서 쓰지 말아주세요 ;ㅅ;ㅠ

**Comment by taeguk** [comment]
시간날때 해보겠습니다!!

**Comment by minhoryang** [comment]
이거 곧 @SGCSRelease/awesometitle 에서 업적으로 만들어 드릴테니, 여기서는 통촉하여 주시옵소서.
SGCSRelease/AwesomeTitle#80
