### ISSUE TITLE
귀 달린 후드 공동구매 하실 분 모아요~

### ISSUE THREAD

**Issue by ddyokim** [SGCSRelease/ReleaseWorld#57]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @dhdh6190
#### 설명:

안녕하세요 릴리즈 14 김도현 입니다.
제가 귀가 달린 후드를 너무 사고 싶어 죽을 것 같습니다. (엉엉 못본 눈 삽니다-)

> 이런들 엇더며 져런들 엇더료
>  만수산(萬壽山) 드렁칡이 얼거진들 엇더리
>  우리도 이치 얼거져 귀달린 후드티 누리리라.

눈을 감아도 떠오르고 눈을 떠도 떠오르니 구매하지 않으면 여러분들 후회하실 거에요-(찡긋)
참여하실 분들은 댓글 달아주세요 헤헤.
#### 확인:
- [x] @JimJeon

**Comment by ddyokim** [comment]
@yunitto

**Comment by JimJeon** [comment]
와아아아아아!!!

**Comment by juice500ml** [comment]
원래 귀달린 후드로 하게되면 로고도 박습니당!

**Comment by ddyokim** [comment]
@minhoryang

**Comment by ddyokim** [comment]
![2016-03-31 7 28 17](https://cloud.githubusercontent.com/assets/10115416/14173073/c5334094-f776-11e5-8a00-6ab1099e3ff6.png)

~~http://www.amazon.com/dp/B018KLOECK?psc=1~~
한국 배송이 안된대요

**Comment by ddyokim** [comment]
![image](https://cloud.githubusercontent.com/assets/10115416/14173313/1d7ae33c-f778-11e5-9f5f-8245f58565a3.png)

얘는 국내 배송이라 배송이 빠를 것 같아요.
http://www.teeclub.co.kr/shop/goods/goods_view.php?goodsno=3787&category=021

**Comment by minhoryang** [comment]
사요!

**Comment by minhoryang** [comment]
어타 후드를 귀달린걸로 할까요?

**Comment by yunitto** [comment]
저욧!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ddyokim** [comment]
좋아요!!!!!!!!!!!!!!!저는 어타는 아니지만!!!!!!!!!!!

**Comment by ddyokim** [comment]
@fuzzythecat 
@mandoriiiii 
@taeguk 
귀 사자 닝겐들!

**Comment by dhdh6190** [comment]
@mandoriiiii

**Comment by yunitto** [comment]
@fuzzythecat  @mandoriiiii 는 이미 필참입니다(엄격 진지 근엄)

**Comment by yunitto** [comment]
@jmg7173

**Comment by mandoriiiii** [comment]
조용히 꽃 한송이 놓고갑니다..
@}-------'--------

**Comment by minhoryang** [comment]
이번기회에 어타오세욧!!!!!!

**Comment by yunitto** [comment]
@SGsupernova

**Comment by taeguk** [comment]
나두 사구싶퍼

**Comment by fuzzythecat** [comment]
토토로 진짜 각인데 ㅠㅠ
아래것도 생각보다 괜찮다

오 귀달면 어타갈수있나요 🌝🌝🌝

**Comment by diana917** [comment]
꺄 저두요!!

**Comment by minhoryang** [comment]
거의 9명 이상이 모였는데요..... 구매 진행하는건가요ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by ddyokim** [comment]
네 진행합시다! 어섬타이틀 로고를 박는다면 로고부터 정해야할거같아요!

**Comment by minhoryang** [comment]
어타 로고 안넣어도되욬ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by kokosake** [comment]
저도 사고 싶어요 ㅠㅜ

**Comment by honamgyu** [comment]
저요!!!!!!!!

**Comment by gumgood** [comment]
저도 헤헤

**Comment by juice500ml** [comment]
새로 톡방을 파던가 해서 어타 로고 박는다. vs. 안박는다. 를 하죠!
