### ISSUE TITLE
웹디자인 스터디를 진행해 봐요

### ISSUE THREAD

**Issue by kokosake** [SGCSRelease/ReleaseWorld#58]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  X
- **관련된 이슈들**:
  - 부모 이슈:
  - 자식 이슈: 
- **추천하고 싶은 사람**: 
#### 설명:

이번에 16학번으로 새로 들어오게 되었습니다.
지금 C Study랑 Java Study가 이뤄지고 있는데,
이렇게 백엔드 쪽을 공부하는 것도 좋지만
공돌이라도 배워두면 좋은?! 프론트엔드 쪽을 공부하는 스터디가 있었으면 좋겠어요

그래서 웹디자인 스터디를 한 번 만들어볼까 해요

진행은, Node.js로 만들어진 블로깅 플랫폼 [Ghost](http://ghost.org)의 테마를 만들어서
결과적으로 스터디원 모두가 자신만의 디자인이 깃들어 있는 블로그를 만들어 보는 방향으로 할 예정입니다

Bootstrap같은 걸 쓰는 것도 좋지만 처음부터 자기가 직접 만들어 보는 것도 좋다고 생각해요

누추하지만 제 디자인 성과물은
- http://wiki.akarus.com: 2015. 05.
- http://regi.kr: 2016. 02.

에서 확인하실 수 있습니다

관심 있으신 분 글 달아 주세요~^^

**Comment by taeguk** [comment]
HTML5, CSS, 웹퍼블리싱, 웹표준 이런거 말씀하시는거죠??!! 막 포토샵하고 이런 디자인이 아니라!

**Comment by taeguk** [comment]
위키랑 블로그 너무 예뻐요!! 위키 글씨체 너무 맘에듬,,,

**Comment by kokosake** [comment]
네 포토샵같은 건 저도 잘 못 다뤄서..ㅠㅜ
기본적인 HTML/CSS/jQuery 정도만 다룰 예정이예요

**Comment by ddyokim** [comment]
우와!!! 블로그 진짜 예뻐요! 레기.kr 이름 귀여워욬ㅋㅋㅋㅋㅋㅋ

**Comment by minhoryang** [comment]
이번 세미나 데이에서 한시간정도의 세미나로 들을 수 있을까요? (4월 30일 (토) #46)

**Comment by kokosake** [comment]
한 시간 정도면 뭐 사실 부족하긴 한데 일단 해 보기는 해 볼게요

**Comment by minhoryang** [comment]
@kokosake 시간이 더 필요하시면 #46에서 말해주세요.
이 이슈는 닫을까요?

**Comment by kokosake** [comment]
네~
