### ISSUE TITLE
뒷풀이 장소 예약

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#6]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [x] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 개강총회`
- **관련된 이슈들**:
  - 부모 이슈:   개총 준비 #2 
  - 자식 이슈:   `없음`
- **추천하고 싶은 사람**:  @tmdghks0612
#### 설명:

뒷풀이 장소 예약해주세요 하쾌장님
#### 확인:
- [x] **@JimJeon**
- [x] **@tmdghks0612**

**Comment by juice500ml** [comment]
위키 참고해주세요.
"여기서 대외란, 외부 인원만이 대상인 이벤트(대외 홍보/선발) 를 의미합니다."
이미 선발이 완료가 되었으니 외부 인원이 아니겠죠?

**Comment by juice500ml** [comment]
논란의 여지가 있어 다시 Label을 원상태로 돌렸습니다. Issue #10 에서 이어서 토론해주세요.

**Comment by juice500ml** [comment]
@tmdghks0612 예약 완료된 경우 카톡 활성원방에 공지를 해주시면 @JimJeon 이 fix되었다는 comment와 함께 Close하면 될 것 같습니다.

**Comment by tmdghks0612** [comment]
3월 16일 7시 반에 홍등롱에서 하는 것으로 예약되었어요!

**Comment by JimJeon** [comment]
close 제가 하겠습니다. @tmdghks0612

**Comment by JimJeon** [comment]
활성회원방에 공지 해주세요.
늦참하는 사람들이 있을 수 있기 때문에
뒷풀이를 홍등롱에서 한다는 점을 명시해 주셨으면 합니다.
