### ISSUE TITLE
소풍을 간다면 캠핑은 어떤가요?

### ISSUE THREAD

**Issue by minhoryang** [SGCSRelease/ReleaseWorld#60]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  다음 소풍!
- **관련된 이슈들**:
  - 부모 이슈:  #55 (이번학기에 할 행사?)
  - 자식 이슈:  
- **추천하고 싶은 사람**:  
#### 설명:

캠핑장 좋아요!
- [난지캠핑장 예약](http://ticket.interpark.com/Ticket/Goods/GoodsInfo.asp?GoodsCode=16001375)
  - 난지캠핑장은 상암월드컵경기장쪽 한강 근처에 위치해있구요, 텐트와 함께 고기를 구워먹을 수 있습니다.
- [노을캠핑장 예약](http://ticket.interpark.com/Ticket/Goods/GoodsInfo.asp?GoodsCode=16002834)
  - 노을캠핑장은 난지캠핑장 위의 산 속에서 한강을 바라보며 텐트를 치고(?!) 고기를 구워먹을 수 있어요!
#### 확인:
- [ ] **@JimJeon**
- [ ] @Assignee

**Comment by yunitto** [comment]
좋아요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by taeguk** [comment]
I agree about that!

**Comment by JimJeon** [comment]
캠핑 좋죠!!! 바비큐하아하아 조오타

**Comment by minhoryang** [comment]
예약은 한달전에해야해요. 우선 이 이슈는 닫을게요.
