### ISSUE TITLE
1번 컴퓨터 마우스가 이상합니다.

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#61]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `가능한 빨리`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**: @?
#### 설명:

클릭이 잘 되지 않습니다.  
전혀 클릭이 되지 않다가 가끔 먹는가 하면 왼쪽 오른쪽 모두 오른쪽으로 인식하기도 하고 사용에 불편함이 있습니다.
터치가 잘 되지 않습니다.  
휠 관련도 전혀 작동이 안되며 각종 쓸어넘기기 두번터치 등 기능이 먹지 않습니다.

확인하시고 교체나 수리 부탁드립니다.
#### 확인:
- [ ] @JimJeon

**Comment by minhoryang** [comment]
이거 프린터 밑의 캐비넷에 새 키보드있는것 처럼 준비되어 있지 않을까용? ㅇㅅㅇ

**Comment by JimJeon** [comment]
오늘 확인했는데 여분 키보드 한 개만 있고 마우스는 없더라고요!
그래서 수리를 맡기는 것이 어떨까 생각하고 있습니다!

**Comment by minhoryang** [comment]
- 입구 옆 LostAndFound 캐비넷 밑에 여분의 키보드와 마우스가 있음을 대청소(#62)에서 확인했습니다.
- 기존의 마우스를 블루투스 설정에서 이름을 바꾸고 삭제하였으며,
- 새 마우스를 연결해 놓았습니다.
  ![kakaotalk_photo_2016-05-01-17-47-58_90|thumbnail](https://cloud.githubusercontent.com/assets/1270855/14940925/ef7ea832-0fc4-11e6-87eb-92a8f671b4fe.jpeg)
