### ISSUE TITLE
간단한 청소를 해주세요

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseWorld#62]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `빨리빨리`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @SGCSRelease/team 
#### 설명:

시험이 끝났어요!
랩실에 지우개 똥과 각종 쓔레기들이 굴러다니네요....
한 번 간단하게 청소를 해야하지 않을까요?
#### 확인:
- [ ] @JimJeon
- [ ] @tmdghks0612

**Comment by minhoryang** [comment]
청소 완료!

ThanksTo @JimJeon @SGsupernova @tmdghks0612 @yunitto @용혁이 @윤영이 + ...
