### ISSUE TITLE
이해민 선배님 세미나 (9월 3일 토요일 @ 판교, 11:00-2:00)

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#65]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160528 #3차 릴리즈데이`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @SGCSRelease/team 
#### 설명:

5월 말 3차 릴리즈데이에 진행될 예정인 이해민 선배님(현 Google Korea product manager)의 세미나에서

궁금한 점들을 적어주세요!

세미나 주제선정에 도움이 됩니다.
#### 확인:
- [ ] @JimJeon
- [ ] @Assignee

**Comment by tmdghks0612** [comment]
우리 학회는 프로젝트 학회니까 프로젝트를 어떻게 진행하는지, 어떻게 협업하는지, 어떤 과정을 거쳐 아이디어를 내는지 등을 세미나 해주시면 좋을 것 같아요.
구글에 관해서 궁금한 점이 있으시면 그런 것도 좋은 질문이 될 것 같아요.

**Comment by taeseunglee** [comment]
구글에서 생각하는 학부생이 알아야할 자료구조, 알고리즘 수준이 있는지, 있다면 얼마나 될까요?
구글에서 구글러들과 일반 대학생을 대상으로 진행하는 교육들은 무엇이 있나요?

**Comment by taeguk** [comment]
소프트웨어 엔지니어에게 가장 필요한 덕목과 공부의 방향성 혹은 태도

**Comment by minhoryang** [comment]
네 위의 질문을 전달해볼게요.
원하는 날짜를 알려주세요.

**Comment by minhoryang** [comment]
죄송해요. 제가 정신이 없어서 전달하지 못했어요.
다음 주 안으로 선배님과 대화를 꼭 나눠보겠습니다.
전달 할 주제는
- "우리 학회는 프로젝트 학회니까 프로젝트를 어떻게 진행하는지, 어떻게 협업하는지, 어떤 과정을 거쳐 아이디어를 내는지 등을 세미나 해주시면 좋을 것 같아요."
- "구글에 관해서 궁금한 점이 있으시면 그런 것도 좋은 질문이 될 것 같아요."
- "구글에서 생각하는 학부생이 알아야할 자료구조, 알고리즘 수준이 있는지, 있다면 얼마나 될까요?"
- "구글에서 구글러들과 일반 대학생을 대상으로 진행하는 교육들은 무엇이 있나요?"
- "소프트웨어 엔지니어에게 가장 필요한 덕목과 공부의 방향성 혹은 태도"

+
- "구글러가 느끼기에 좋은 동료는 누구인가? 그리고 좋은 동료는 어떻게 될까?"
- "현재 구글 내에서 벌어지고 있는 재미난 일"
- "구글에서 느낄 수 있는 컬쳐쇼크들은?"
- "구글러들이 당연하게 생각하는 점들"

원하는 일자는 주말로 해서 제가 알아보겠습니다.

이 이슈는 제가 가져가겠습니다.

**Comment by minhoryang** [comment]
@SGCSRelease/team Let's Go!
참가자를 9월 1일까지 모집합니다!

**Comment by taeseunglee** [comment]
참가 손!

**Comment by jmg7173** [comment]
저욧!

**Comment by ddyokim** [comment]
손!

**Comment by raon0211** [comment]
저요!

**Comment by juice500ml** [comment]
Hand!

**Comment by minhoryang** [comment]
구글드라이브의 `2016 Release > Release 행사자료 > 이해민 선배님 세미나 (160903, Google PM)` 에 사진을 올려두었습니다. 발표하실 때 쓰세요.
