### ISSUE TITLE
삼성 SDS 채용 관련 설명회가 들어왔어요!

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#66]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160516`
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @SGCSRelease/team 
#### 설명:

삼성 SDS에서 저희 학회를 대상으로 설명회를 진행하려 합니다.

다음주인 5월 16일 월요일까지 답변을 주면, 저희가 원하는 장소에 원하는 시간으로 채용 설명회를 잡아주신다고 합니다.

세미나를 진행하는게 좋을지 여부나 진행한다면 언제 진행했으면 좋겠는지 의견 있으시면 올려주세요.

**Comment by jmg7173** [comment]
설명회 끝났으니 이슈 닫겠습니다.

**Comment by minhoryang** [comment]
오늘 진행했고, 10명정도 참여하였습니다.
