### ISSUE TITLE
5/28 (토) 세번째 릴리즈 데이를 준비해야해요!

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#69]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160315 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈:   #67 
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @SGCSRelease/16-spring 
#### 설명:

5월 28일에 릴리즈 데이를 진행합니다!
잠정적으로는 LG해커톤을 진행하는걸로 알고있는데 진행하는 내용이나 혹시 릴데이에 관해 수정할 사항 있으면 Comment 달아주세요
#### 확인:
- [x] @tmdghks0612 
- [ ] @yunitto 
- [ ] @JimJeon 
- [ ] @charcoalbug 
- [x] @chldlftjs 
- [x] @jmg7173

**Comment by jmg7173** [comment]
LG해커톤 토요일에 진행할건지 말건지 확정합시다!

**Comment by mandoriiiii** [comment]
LG해커톤은 토요일 진행 확정 아닙니다!
세미나에서 lg측과 협의 후 결정입니다 ㅠㅠ

**Comment by jmg7173** [comment]
LG 해커톤 및 세미나 관련된 내용 중 픽스된 내용입니다!
1. 아직 토요일에 해커톤 할지 말지 LG측과 협의가 되지 않은 상태입니다. 일단 평소대로 릴리즈데이를 진행할 예정입니다.
2. (만약 해커톤을 한다면) 해커톤 참여 하려면 목요일 세미나 참석이 꼭 필요합니다. (적어도 팀당 1명)
3. 그렇기 때문에 해커톤 할 팀원을 구해야합니다(반드시 2~3명 혼자는 안돼요!)

**Comment by tmdghks0612** [comment]
blender 로 3d 모델링에 관해서 간단하게 실습 같은 거 하면서 진행해볼까 하는데 세미나 가능할까요

**Comment by juice500ml** [comment]
업데이트 해주세요~ @jmg7173

**Comment by jmg7173** [comment]
5/28일 릴리즈 데이는 6월 18일에 종총과 함께 진행되었습니다.
#70
