### ISSUE TITLE
마일스톤 이름 제안

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseWorld#7]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160314`
- **관련된 이슈들**:
  - 부모 이슈:   `null`
  - 자식 이슈:   `null`
- **추천하고 싶은 사람**:  @JimJeon 
#### 설명:

`첫 번째 세미나/모임` 이라는 이름 대신에 `3월 Release Day`로 하는건 어떨까요?
#### 확인:
- [x] **@JimJeon**

**Comment by JimJeon** [comment]
Release Day 이름 좋다 ㅎㅎ
대신에 학회장님 ( @tmdghks0612 ) 개강총회 때 회원들한테 Release Day가 무엇인지 설명해주세요!
- [x] 학회장 승인

**Comment by tmdghks0612** [comment]
@JimJeon 설명하도록 하겠습니다.
