### ISSUE TITLE
종강총회를 준비해요!

### ISSUE THREAD

**Issue by tmdghks0612** [SGCSRelease/ReleaseWorld#70]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:
- **관련된 이슈들**:
  - 부모 이슈:  
  - 자식 이슈:  
- **추천하고 싶은 사람**:  
#### 설명:

  종강총회 날짜 및 스케쥴을 결정해야 해요.

현재 상황 감안했을 때 기말고사 후가 더 좋을 거라고 생각하는데 어떻게 생각하시나요?

그리고 종강총회에서 진행해야 할 스케쥴과 공지사항도 적어주세요!
#### 확인:
- [ ] @JimJeon
- [ ] @Assignee

**Comment by tmdghks0612** [comment]
일단 취소됐었던

허남규의 'vim1(비밀) 세미나'
주제:vim

최승환의 '너! 내 안경이 되라!'
주제: 3d 모델링

이 두 세미나 그리고 엠티 관련해서도 공지가 필요할 것 같습니다.

**Comment by chldlftjs** [comment]
기말고사 후에 할 생각이면 학회원들이 다 언제쯤 시험이 끝나는지 알아볼 필요가 있을 것 같네요.

**Comment by honamgyu** [comment]
밤샘 뒷풀이 이벤트 있었으면 좋겠어요!

**Comment by jmg7173** [comment]
17~25일 사이에 했으면 좋겠어요. 18일에 릴리즈데이 겸 하는 건 어떨까요?

**Comment by tmdghks0612** [comment]
6월 릴리즈데이를 그 때로 당긴다면 좋을 것 같네요. 게다가 토요일이면 람큐 말대로 밤샘 뒷풀이가 가능할지도?!

**Comment by honamgyu** [comment]
시험 끝나고 밤새서 세미나 준비해야겠네요..!

**Comment by yunitto** [comment]
타임캡슐을 만드는게 어때요? 10년후의 자기자신과 릴리즈에게요! +_+

**Comment by taeguk** [comment]
@yunitto 좋아요!!!

**Comment by ddyokim** [comment]
앗 저도 그때 세미나를 하고 싶지만 저는 6월 18일이 어려워요ㅠㅠ타임캡슐은 좋아요!

**Comment by chldlftjs** [comment]
기숙사에 계시는 분들을 생각하면 18일부터는 무리일 것 같아요. 18일 토요일에 기숙사를 나오는 것 같더라고요.

**Comment by yunitto** [comment]
이해민 선배님 세미나에서 할 질문 이때까지 확정지어요

**Comment by yunitto** [comment]
+20일에 있을 대청소를 준비해요

**Comment by jmg7173** [comment]
종총 때 진행한 드라이브에 세미나 올려주세요
@tmdghks0612 @honamgyu 
그리고 회칙 바뀐거 커밋해주세요
@JimJeon

**Comment by tmdghks0612** [comment]
세미나 내용 업데이트 했고요 짐전이 회칙 변경도 완료했네요 이슈닫을게요
