### ISSUE TITLE
AwesomeTitle을 같이 개발할 분들을 구합니다!

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#73]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈:  #72 
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @SGCSRelease/team 
#### 설명:

Release의 별명 업적 관리 서비스인 AwesomeTitle을 같이 개발할 사람을 모집합니다!
- 프론트엔드 하실 분 구합니다.
- DB 관리하실 분 구합니다.
- 새로운 아이디어로 기능을 추가하실 분 구합니다.
- 기존의 기능에 있던 버그를 발견하고 Fix할 분을 구합니다.

**Comment by yunitto** [comment]
ME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by juice500ml** [comment]
ㅋㅋㅋㅋㅋ

**Comment by AilisObrian** [comment]
+1

**Comment by minhoryang** [comment]
+1!

**Comment by raon0211** [comment]
아 실수로 closed 눌렀어요! 모바일에서는 comment 버튼 바로 옆에 close 버튼이 있네요! 저 프론트엔드랑 백엔드 조금 해볼게요 ^^
