### ISSUE TITLE
릴리즈 MT때 무엇을 하고 싶나요?

### ISSUE THREAD

**Issue by jmg7173** [SGCSRelease/ReleaseWorld#74]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  
- **관련된 이슈들**:
  - 부모 이슈:   #71 
  - 자식 이슈:  
- **추천하고 싶은 사람**:  @SGCSRelease/team 
#### 설명:

7월 1~2일에 진행할 릴리즈 MT에서 재밌게 놀기 위한 아이디어를 모집하고 있어요! 많은 아이디어 부탁드립니다.

**Comment by tmdghks0612** [comment]
물총 가져가고 싶어요!

**Comment by juice500ml** [comment]
agar.io
sliter.io
diep.io

**Comment by mandoriiiii** [comment]
몰래카메라요

**Comment by honamgyu** [comment]
무한도전식 술래잡기!

**Comment by honamgyu** [comment]
포커!
