### ISSUE TITLE
개총 PPT에 들어갈 내용1.스터디 수요조사

### ISSUE THREAD

**Issue by yunitto** [SGCSRelease/ReleaseWorld#8]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 #개강총회`
- **관련된 이슈들**:
  - 부모 이슈:   #1 #2 #3  
  - 자식 이슈:  
- **추천하고 싶은 사람**: @tmdghks0612  @JimJeon 
#### 설명:

1.개강총회 때 신입생들이 원하는 스터디를 조사하고 취합합니다. --> 피피티에 넣어주세요!
- 요청이 예상되는 스터디 : C언어, 파이썬...

2.선배들이 진행할 수 있는 스터디를 조사합니다. 할 수 있는 선배가 있다면 일주일에 얼마정도 시간을 할애할 수 있는지도 물어보면 좋겠죠.
#### 확인:
- [x] **@JimJeon**
- [x] @chldlftjs

**Comment by yunitto** [comment]
바빠서 글 형식을 좀 못지켰는데ㅠㅠ 누구든 좀 부탁드릴게요!

**Comment by yunitto** [comment]
일단 14학번 분들께 개인적으로 컨택해서 어떤 스터디를 해주실 수 있는지 각각 물어보겠습니다.15학번 분들께 여쭤보는건 @tmdghks0612 @charcoalbug @chldlftjs 이 상의하고 맡아주세요.

**Comment by juice500ml** [comment]
언어 기준(C, Python, Java ... )
만드는 것 기준(Mobile app, Web service, Game development ...)
주제 기준(Github, Programming Style, Design Pattern ...)
기준은 많을 수 있어요! 굳이 C/Python으로 고민하지 않으면 좋겠어요.
덧붙이자면, 꼭 학번을 구분하지 않고 스터디를 했으면! 16도 스터디의 주체가 되어도 좋아요!

@yunitto @tmdghks0612 @JimJeon

**Comment by JimJeon** [comment]
이부분은 일선이형에게 맡기겠습니다.

**Comment by jmg7173** [comment]
1위 : JAVA 및 Android (8명)
2위 : Swift (5명)
3위 : Python (4명)
4위 : C (0명 ㅠㅠ)
