### ISSUE TITLE
개총 PPT에 들어갈 내용2.랩실 관리 방법 교육

### ISSUE THREAD

**Issue by yunitto** [SGCSRelease/ReleaseWorld#9]
- [X] **[이슈 작성법](../wiki/Issues-규칙)을 읽고 왔습니다.**
- [X] 바람직한 제목을 적어주시고, 오른쪽 메뉴에서 **라벨**과 **마일스톤**을 선택했어요.
- **해결되어야 하는 마감일**:  `160316 개강총회`
- **관련된 이슈들**:
  - 부모 이슈:   #1 #2 #3  
  - 연관 이슈:  [#8. 개총PPT에 들어갈 내용1.스터디 수요조사](#8)  
  - 자식 이슈: x
- **추천하고 싶은 사람**:  @juice500ml 이 꼼꼼하게 잘하니까 해주면 좋을거같아요!
#### 설명:

@tmdghks0612 다음주부터는 정식 관리 시간표대로 관리를 해야하겠죠? 언제언제 시간되는지는 나중에 취합하더라도 관리교육은 개총 때 하면 좋을거같아요! 한번에 이렇게 사람모으는게 쉬운일이 아니니까요 :)
#### 확인:
- [x] **@JimJeon**

**Comment by juice500ml** [comment]
@yunitto Assignee 자리에 @tmdghks0612 를 태그해주세요!

**Comment by JimJeon** [comment]
이건 제가 하겠습니다. 광희한테 하나라도 덜 맡기고 싶어요.

**Comment by JimJeon** [comment]
제가 자료구조 오픈랩이 개강총회 당일 생겨서 못 갈 수도 있어요....
윤영이에게 발표를 넘기겠습니다.

발표준비는 돕도록 하겠습니다.

**Comment by jmg7173** [comment]
이제 잘 관리할 수 있으리라 믿어요!
